/**
 * HIKMAT TANI - Seed Data Awal & Pustaka Agronomi Terverifikasi
 * 
 * Standar Data:
 * - Sumber resmi dari BBPadi Sukamandi (Litbang Pertanian / BRIN), Ditlin Kementan RI, Balittanah, dan IRRI.
 * - Tanpa data fiktif atau mengarang rekomendasi agronomi.
 * - Format ID konsisten dan unik untuk mencegah duplikasi.
 */

import {
  Fertilizer,
  KnowledgeArticle,
  NaturalEnemy,
  Opt,
  Reference,
  RiceVariety,
} from '../types/index.ts';

export const SEED_REFERENCES: Reference[] = [
  {
    id: 'ref-litbang-padi-2020',
    title: 'Petunjuk Teknis Budidaya Padi Sawah Irigasi Berorientasi IP 400',
    authorInstitution: 'Balai Besar Penelitian Tanaman Padi (BBPadi) Sukamandi - Badan Litbang Pertanian',
    publicationYear: 2020,
    sourceUrlOrBook: 'Buku Juknis BBPadi Sukamandi Kementan RI',
    regionApplicability: 'Nasional / Sawah Irigasi & Tadah Hujan',
    validationStatus: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ref-pht-padi-2019',
    title: 'Pedoman Pengendalian Hama Terpadu (PHT) Tanaman Padi',
    authorInstitution: 'Direktorat Perlindungan Tanaman Pangan, Ditjen Tanaman Pangan Kementan RI',
    publicationYear: 2019,
    sourceUrlOrBook: 'Buku Pedoman Ditlin Tanaman Pangan Jakarta',
    regionApplicability: 'Nasional',
    validationStatus: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ref-pupuk-kementan-2021',
    title: 'Rekomendasi Pemupukan N, P, dan K Spesifik Lokasi untuk Tanaman Padi Sawah',
    authorInstitution: 'Balai Penelitian Tanah (Balittanah) Bogor - Kementan RI',
    publicationYear: 2021,
    sourceUrlOrBook: 'Permentan Rekomendasi Pupuk N, P, K Spesifik Lokasi',
    regionApplicability: 'Nasional',
    validationStatus: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ref-irri-rice-knowledge',
    title: 'Rice Knowledge Bank - Alternate Wetting and Drying (AWD) & Integrated Pest Management',
    authorInstitution: 'International Rice Research Institute (IRRI) Los Baños',
    publicationYear: 2022,
    sourceUrlOrBook: 'IRRI Agronomy & Crop Management Compendium',
    regionApplicability: 'Asia Tenggara / Tropis',
    validationStatus: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ref-brin-varietas-2023',
    title: 'Deskripsi Varietas Unggul Baru Padi Sawah dan Profil Ketahanan Cekaman Biotik/Abiotik',
    authorInstitution: 'Pusat Riset Tanaman Pangan - Organisasi Riset Pertanian dan Pangan BRIN',
    publicationYear: 2023,
    sourceUrlOrBook: 'Katalog Varietas Unggul Padi BRIN',
    regionApplicability: 'Nasional',
    validationStatus: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ref-bbpopt-tikus-2021',
    title: 'Teknologi Pengendalian Hama Tikus Sawah Berbasis Trap Barrier System (TBS)',
    authorInstitution: 'Balai Besar Peramalan Organisme Pengganggu Tumbuhan (BBPOPT) Jatisari',
    publicationYear: 2021,
    sourceUrlOrBook: 'Jurnal Perlindungan Tanaman Pertanian BBPOPT',
    regionApplicability: 'Nasional',
    validationStatus: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

export const SEED_FERTILIZERS: Fertilizer[] = [
  {
    id: 'fert-urea',
    name: 'Urea (Prill/Granul)',
    type: 'INORGANIC_SINGLE',
    formula: '46-0-0',
    nutrientComposition: { N: 46 },
    aliases: ['Urea', 'Nitrogen', 'Pupuk Putih'],
    referenceId: 'ref-pupuk-kementan-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'fert-sp36',
    name: 'SP-36 (Super Phosphate)',
    type: 'INORGANIC_SINGLE',
    formula: '0-36-0 + 5S',
    nutrientComposition: { P2O5: 36, S: 5 },
    aliases: ['SP36', 'SP-36', 'Fosfat'],
    referenceId: 'ref-pupuk-kementan-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'fert-kcl',
    name: 'KCl (Kalium Klorida / MOP)',
    type: 'INORGANIC_SINGLE',
    formula: '0-0-60',
    nutrientComposition: { K2O: 60 },
    aliases: ['KCl', 'MOP', 'Pupuk Merah', 'Kalium'],
    referenceId: 'ref-pupuk-kementan-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'fert-za',
    name: 'ZA (Zwavelzure Amoniak)',
    type: 'INORGANIC_SINGLE',
    formula: '21-0-0 + 24S',
    nutrientComposition: { N: 21, S: 24 },
    aliases: ['ZA', 'Amonium Sulfat', 'Sulfur'],
    referenceId: 'ref-pupuk-kementan-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'fert-npk-ponska',
    name: 'NPK Phonska (15-15-15 + 10S)',
    type: 'INORGANIC_COMPOUND',
    formula: '15-15-15 + 10S',
    nutrientComposition: { N: 15, P2O5: 15, K2O: 15, S: 10 },
    aliases: ['Phonska', 'NPK Phonska', 'NPK 15-15-15'],
    referenceId: 'ref-pupuk-kementan-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'fert-npk-16-16-16',
    name: 'NPK Mutiara / Kujang (16-16-16)',
    type: 'INORGANIC_COMPOUND',
    formula: '16-16-16',
    nutrientComposition: { N: 16, P2O5: 16, K2O: 16 },
    aliases: ['NPK 16', 'NPK Biru', 'NPK Kujang 16'],
    referenceId: 'ref-pupuk-kementan-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'fert-kompos-kandang',
    name: 'Pupuk Kandang Sapi Matang / Kompos',
    type: 'ORGANIC',
    formula: 'Organik Terfermentasi Matang',
    nutrientComposition: { N: 1.5, P2O5: 1.0, K2O: 1.5, Ca: 0.8, Mg: 0.5 },
    aliases: ['Pukan', 'Pupuk Kandang', 'Kohe Sapi', 'Kompos Matang'],
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'fert-dolomit',
    name: 'Kapur Pertanian / Dolomit (CaCO3 + MgCO3)',
    type: 'INORGANIC_SINGLE',
    formula: 'CaMg(CO3)2',
    nutrientComposition: { Ca: 30, Mg: 18 },
    aliases: ['Dolomit', 'Kaptan', 'Kapur Pertanian'],
    referenceId: 'ref-pupuk-kementan-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

export const SEED_VARIETIES: RiceVariety[] = [
  {
    id: 'var-inpari-32',
    name: 'Inpari 32 HDB',
    aliases: ['Inpari 32', 'Ciherang Baru'],
    growthDurationDays: 120,
    potentialYieldKgHa: 8420,
    resistanceProfile: 'Tahan Hawar Daun Bakteri (HDB) strain III, IV, VIII; Agak tahan Blas',
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-ciherang',
    name: 'Ciherang',
    aliases: ['Ciherang Asli', 'IR64 Turunan'],
    growthDurationDays: 116,
    potentialYieldKgHa: 8500,
    resistanceProfile: 'Tahan Wereng Batang Coklat biotipe 2 dan 3; Agak tahan HDB strain III',
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-inpari-42',
    name: 'Inpari 42 Agritan GSR',
    aliases: ['Inpari 42', 'Green Super Rice'],
    growthDurationDays: 112,
    potentialYieldKgHa: 10580,
    resistanceProfile: 'Tahan Blas, Tahan HDB strain III, Toleran kekeringan/efisiensi hara',
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-mekongga',
    name: 'Mekongga',
    aliases: ['Mekongga Sukamandi'],
    growthDurationDays: 118,
    potentialYieldKgHa: 8400,
    resistanceProfile: 'Tahan Wereng Batang Coklat biotipe 2 dan 3; Agak tahan HDB strain IV',
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-situ-bagendit',
    name: 'Situ Bagendit',
    aliases: ['Bagendit', 'Padi Gogo Bagendit'],
    growthDurationDays: 110,
    potentialYieldKgHa: 6000,
    resistanceProfile: 'Sangat cocok untuk sawah tadah hujan & lahan kering (gogo); Toleran kekeringan',
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-sintanur',
    name: 'Sintanur',
    aliases: ['Sintanur Wangi', 'Padi Aromatik'],
    growthDurationDays: 115,
    potentialYieldKgHa: 7200,
    resistanceProfile: 'Beras pulen aromatik pandan wangi; Agak tahan HDB strain III',
    referenceId: 'ref-brin-varietas-2023',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-inpari-48-blas',
    name: 'Inpari 48 Blas',
    aliases: ['Inpari 48'],
    growthDurationDays: 115,
    potentialYieldKgHa: 9130,
    resistanceProfile: 'Tahan Blas Daun dan Leher ras 033, 073, 133; Tahan WBC biotipe 1, 2, 3',
    referenceId: 'ref-brin-varietas-2023',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-ir64',
    name: 'IR64',
    aliases: ['IR-64 Klasik'],
    growthDurationDays: 115,
    potentialYieldKgHa: 7000,
    resistanceProfile: 'Varietas tetua legendaris; Rasa nasi sangat pulen; Agak rentan wereng biotipe 3 baru',
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

export const SEED_OPTS: Opt[] = [
  {
    id: 'opt-penggerek-kuning',
    commonName: 'Penggerek Batang Padi Kuning (PBPK)',
    scientificName: 'Scirpophaga incertulas',
    category: 'INSECT_PEST',
    aliases: ['Sundep', 'Beluk', 'Ulat Penggerek', 'Kaper'],
    symptoms: 'Fase vegetatif: pucuk tanaman mati/kering mudah dicabut bila ditarik (Sundep). Fase generatif: malai hampa keputihan tegak (Beluk).',
    lifeCycle: 'Telur (6-7 hari) -> Larva aktif (28-35 hari) -> Pupa di pangkal batang (6-9 hari) -> Ngengat kaper (4-5 hari). Total 40-55 hari.',
    hostPlants: ['Padi sawah', 'Padi liar (Oryza rufipogon)'],
    vulnerableStage: 'Vegetatif (Pembentukan Anakan) & Primordia/Bunting',
    triggerFactors: ['Pemupukan Urea/N berlebih tanpa imbangan K', 'Penanaman tidak serempak dalam satu hamparan', 'Lampu penerangan malam dekat petak sawah'],
    monitoringMethod: 'Amati rumpun contoh secara diagonal; hitung jumlah kelompok telur berbulu halus dan persentase anakan sundep/beluk.',
    economicThreshold: 'Rata-rata 1 kelompok telur per rumpun atau serangan sundep > 5% pada fase vegetatif awal.',
    culturalControl: 'Tanam serempak dalam hamparan minimal 10 ha, potong pucuk bibit saat pindah tanam, atur pemupukan N seimbang.',
    mechanicalControl: 'Kumpulkan dan musnahkan kelompok telur, pasang lampu perangkap (light trap) 40 watt di sudut sawah.',
    biologicalControl: 'Konservasi tawon parasitoid telur Trichogramma japonicum, Telenomus rowani, serta laba-laba pemburu.',
    chemicalControl: 'Aplikasi insektisida sistemik berbahan aktif terdaftar jika ambang pengendalian terlampaui.',
    activeIngredients: ['Klorantraniliprol', 'Dimehipo', 'Fipronil', 'Kartap Hidroklorida'],
    resistanceNotes: 'Hindari penggunaan bahan aktif golongan yang sama berturut-turut.',
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-wereng-coklat',
    commonName: 'Wereng Batang Coklat (WBC)',
    scientificName: 'Nilaparvata lugens',
    category: 'INSECT_PEST',
    aliases: ['Wereng Coklat', 'WBC', 'Hopperburn'],
    symptoms: 'Tanaman menguning, mengering cepat seperti terbakar melingkar dari tengah petak (Hopperburn); penular virus kerdil rumput & kerdil hampa.',
    lifeCycle: 'Telur (7-9 hari) -> Nimfa 5 instar (12-15 hari) -> Imago dewasa (18-20 hari).',
    hostPlants: ['Padi sawah'],
    vulnerableStage: 'Fase Anakan Maksimum hingga Pemasakan Bulir',
    triggerFactors: ['Penggunaan insektisida piretroid sintetik yang mematikan musuh alami', 'Aplikasi pupuk N dosis tinggi', 'Jarak tanam terlalu rapat tanpa lorong Legowo'],
    monitoringMethod: 'Periksa pangkal batang padi di bawah kanopi daun pada 20 rumpun sampel secara berkala setiap 5-7 hari.',
    economicThreshold: 'Kepadatan rata-rata >= 10 ekor per rumpun pada fase vegetatif, atau >= 20 ekor per rumpun pada fase bunting/generatif.',
    culturalControl: 'Tanam varietas tahan (Inpari 32, Inpari 48), gunakan sistem tanam Jajar Legowo 2:1, terapkan pengairan berselang (AWD).',
    mechanicalControl: 'Keringkan petak sawah selama 3-5 hari untuk menurunkan kelembapan mikro di pangkal rumpun.',
    biologicalControl: 'Laba-laba Pardosa pseudoannulata, kumbang Tomcat Paederus fuscipes, kepik Cyrtorhinus lividipennis, jamur Beauveria bassiana.',
    chemicalControl: 'Gunakan insektisida spesifik penghambat pertumbuhan (IGR) atau sistemik selektif bila populasi melampaui ambang ekonomi.',
    activeIngredients: ['Buprofezin', 'Pimetrozin', 'Triflumuron', 'Dinotefuran'],
    resistanceNotes: 'Hindari insektisida semprot spektrum luas yang dapat memicu ledakan resurgensi wereng.',
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-tikus-sawah',
    commonName: 'Tikus Sawah',
    scientificName: 'Rattus argentiventer',
    category: 'VERTEBRATE_PEST',
    aliases: ['Tikus', 'Hama Pengerat', 'Rattus'],
    symptoms: 'Batang padi terpotong miring membentuk sudut 45 derajat di bagian tengah petak; liang sarang aktif di pematang sawah dan tanggul saluran.',
    lifeCycle: 'Bunting 21 hari, melahirkan 6-12 anak per kelahiran, mampu berkembang biak 3 kali dalam satu musim tanam padi.',
    hostPlants: ['Padi', 'Jagung', 'Ubi jalar', 'Padi liar'],
    vulnerableStage: 'Semua fase, mulai dari Pesemaian, Anakan, hingga Fase Pengisian Bulir/Matang',
    triggerFactors: ['Pematang sawah terlalu lebar/tinggi (>30 cm) yang dijadikan sarang', 'Tanam tidak serempak', 'Sanitasi lingkungan persawahan kotor'],
    monitoringMethod: 'Amati jejak kaki, kotoran segar, liang aktif di pematang, dan persentase rumpun rusak terpotong miring.',
    economicThreshold: 'Ditemukan liang aktif baru atau kerusakan rumpun > 2% pada fase vegetatif awal.',
    culturalControl: 'Tanam serempak dalam hamparan, perkecil pematang sawah (< 30 cm), bersihkan semak dan gulma tanggul.',
    mechanicalControl: 'Gropyokan massal saat olah tanah (pratanam), pasang Sistem Bubu Perangkap (TBS / LTBS), emposan asap belerang pada liang aktif.',
    biologicalControl: 'Pemanfaatan musuh alami burung hantu Tyto alba dengan mendirikan Rumah Burung Hantu (Rubuha) 1 unit per 5 hektar.',
    chemicalControl: 'Umpan rodentisida antikoagulan terdaftar hanya pada awal musim di luar petakan.',
    activeIngredients: ['Kumatetralil', 'Bromadiolon', 'Fosfida Seng (Umpan Akut Terbatas)'],
    referenceId: 'ref-bbpopt-tikus-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-walang-sangit',
    commonName: 'Walang Sangit',
    scientificName: 'Leptocorisa oratorius',
    category: 'INSECT_PEST',
    aliases: ['Walang Sangit', 'Kepik Pengisap Bulir', 'Sangit'],
    symptoms: 'Bulir padi menjadi hampa atau berbintik coklat kehitaman (beras bernoda dan patah saat digiling); tercium bau sengit khas di sawah.',
    lifeCycle: 'Telur diletakkan berbaris pada daun (6-8 hari) -> Nimfa 5 instar (17-25 hari) -> Imago dewasa (50-60 hari).',
    hostPlants: ['Padi sawah', 'Rumput jampang (Digitaria ciliaris)', 'Rumput bebek (Echinochloa colona)'],
    vulnerableStage: 'Fase Masak Susu (Milk Stage) hingga Masak Kuning (Dough Stage)',
    triggerFactors: ['Keberadaan gulma rumput berbiji di pematang sawah', 'Penanaman bertahap tidak serentak'],
    monitoringMethod: 'Gunakan jaring ayun (sweep net) 20 kali ayunan diagonal di atas kanopi malai pada pagi (06.00-08.00) atau sore hari.',
    economicThreshold: 'Rata-rata 5 ekor walang sangit per 20 rumpun pada fase masak susu.',
    culturalControl: 'Pembersihan gulma inang rumput-rumputan di pematang sawah sebelum tanaman padi berbunga.',
    mechanicalControl: 'Gunakan perangkap berumpan bangkai kepiting/keong mas busuk yang digantung di tiang bambu sekitar pematang.',
    biologicalControl: 'Parasitoid telur Gryon nixoni dan jamur Beauveria bassiana.',
    chemicalControl: 'Penyemprotan insektisida berbahan aktif kontak pada pagi atau sore hari saat hama aktif bertengger di atas malai.',
    activeIngredients: ['BPMC (Fenobukarb)', 'MOPC', 'Karbosulfan', 'Deltametrin'],
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-hawar-daun-bakteri',
    commonName: 'Hawar Daun Bakteri (HDB / Kresek)',
    scientificName: 'Xanthomonas oryzae pv. oryzae',
    category: 'DISEASE',
    aliases: ['Kresek', 'HDB', 'Hawar Daun', 'Bacterial Blight'],
    symptoms: 'Bercak kuning kebasahan mulai dari pucuk atau tepi daun, meluas ke bawah menjadi kelabu keputihan berombak; daun layu mengering keriting.',
    lifeCycle: 'Bakteri bertahan pada sisa jerami sakit, gulma inang, dan benih; menular cepat lewat air irigasi dan luka gesekan daun.',
    hostPlants: ['Padi sawah', 'Gulma Leersia hexandra'],
    vulnerableStage: 'Semua fase, terutama Anakan Aktif (gejala Kresek) hingga Fase Bunting/Berbunga (gejala Hawar)',
    triggerFactors: ['Kelembapan tinggi (>85%), angin kencang disertai hujan lebat, dosis pupuk Urea/N berlebih tanpa pupuk K.'],
    monitoringMethod: 'Amati persentase luas permukaan daun yang bergejala pada petak sawah.',
    economicThreshold: 'Kerusakan daun > 10% pada fase anakan atau > 5% pada fase bunting.',
    culturalControl: 'Gunakan varietas tahan (Inpari 32, Inpari 48), hindari pemotongan daun bibit saat tanam, kurangi N, tambah pupuk K (KCl).',
    mechanicalControl: 'Sanitasi pematang dan singgang sisa panen yang terinfeksi.',
    biologicalControl: 'Aplikasi agens hayati bakteri antagonis Paenibacillus polymyxa atau Pseudomonas fluorescens.',
    chemicalControl: 'Bakterisida tembaga atau antibiotik pertanian terdaftar bila serangan meluas dan cuaca ekstrem.',
    activeIngredients: ['Tembaga Hidroksida', 'Tembaga Oksiklorida', 'Kasugamisin', 'Asam Oksolinik'],
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-blas-padi',
    commonName: 'Penyakit Blas Padi',
    scientificName: 'Pyricularia oryzae (Magnaporthe oryzae)',
    category: 'DISEASE',
    aliases: ['Blas Daun', 'Blas Leher', 'Patah Leher', 'Tengik', 'Rice Blast'],
    symptoms: 'Bercak berbentuk belah ketupat runcing di kedua ujung dengan pusat kelabu pada daun; leher tangkai malai membusuk kelabu kehitaman lalu patah (Blas Leher).',
    lifeCycle: 'Konidia jamur disebarkan lewat angin dan percikan embun pada malam hari yang dingin lembap (suhu 24-28°C).',
    hostPlants: ['Padi sawah', 'Padi gogo'],
    vulnerableStage: 'Vegetatif Awal (Blas Daun) & Fase Keluar Malai/Berbunga (Blas Leher)',
    triggerFactors: ['Dosis pupuk N sangat tinggi, tanah kekurangan silika (Si), kelembapan malam tinggi dengan kabut tebal berkepanjangan.'],
    monitoringMethod: 'Periksa daun muda bagian atas dan tangkai leher malai pada 20 rumpun sampel.',
    economicThreshold: 'Ditemukan bercak belah ketupat aktif pada daun bendera atau tanda awal infeksi pada leher malai saat bunting akhir.',
    culturalControl: 'Perlakuan benih (seed treatment), jarak tanam teratur (Jajar Legowo 2:1), pergiliran varietas, pemberian pupuk silika.',
    mechanicalControl: 'Eradikasi rumpun terinfeksi parah di persemaian sebelum pindah tanam.',
    biologicalControl: 'Pemanfaatan agens hayati jamur Trichoderma harzianum atau Trichoderma viride.',
    chemicalControl: 'Fungisida sistemik spesifik berbahan aktif terdaftar saat bunting tua dan saat keluar malai 5-10%.',
    activeIngredients: ['Trisiklazol', 'Isoprotiolan', 'Azoksistrobin', 'Difenokonazol', 'Tebukonazol'],
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-penyakit-tungro',
    commonName: 'Penyakit Tungro Padi',
    scientificName: 'Rice Tungro Bacilliform Virus (RTBV) & Rice Tungro Spherical Virus (RTSV)',
    category: 'DISEASE',
    aliases: ['Tungro', 'Kerdil Kuning', 'Kerdil Oranye', 'Mentek'],
    symptoms: 'Tanaman kerdil nyata, jumlah anakan sedikit, daun muda berwarna kuning jingga/oranye dari ujung memanjang ke bawah, malai keluar tidak sempurna dan hampa.',
    lifeCycle: 'Virus ditularkan oleh serangga vektor Wereng Daun Hijau (Nephotettix virescens) secara semi-persisten.',
    hostPlants: ['Padi sawah', 'Padi liar'],
    vulnerableStage: 'Pesemaian hingga Fase Anakan Aktif (0-30 HST)',
    triggerFactors: ['Populasi wereng hijau tinggi di persemaian, tanam tidak serempak dalam hamparan luas.'],
    monitoringMethod: 'Pantau keberadaan wereng hijau di pesemaian dan gejala daun oranye kekuningan pada rumpun muda.',
    economicThreshold: 'Ditemukan 1 tanaman bergejala tungro per 100 rumpun pada fase sebelum 30 HST.',
    culturalControl: 'Tanam serempak dalam hamparan, pergiliran varietas tahan tungro (Inpari 36, Inpari 37), eradikasi singgang sumber virus.',
    mechanicalControl: 'Cabut dan benamkan segera tanaman kerdil bergejala tungro agar tidak menular.',
    biologicalControl: 'Konservasi laba-laba predator dan pemangsa wereng hijau.',
    chemicalControl: 'Pengendalian ditujukan kepada serangga vektor (Wereng Hijau) dengan insektisida sistemik bila populasi tinggi di persemaian.',
    activeIngredients: ['Imidakloprid', 'Tiametoksam', 'Dimehipo'],
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-keong-mas',
    commonName: 'Keong Mas',
    scientificName: 'Pomacea canaliculata',
    category: 'MOLLUSC_PEST',
    aliases: ['Keong Mas', 'Siput Murbai', 'Siput Murbei'],
    symptoms: 'Batang dan helaian daun bibit padi muda terpotong pangkalnya dan mengapung di permukaan air; rumpun di persemaian atau sawah baru habis.',
    lifeCycle: 'Telur berwarna merah muda diletakkan berkelompok di atas permukaan air (7-14 hari) -> Anak keong rakus -> Dewasa (usia hidup 2-3 tahun).',
    hostPlants: ['Bibit padi muda (0-15 HST)', 'Kangkung', 'Eceng gondok'],
    vulnerableStage: 'Pesemaian & Fase Bibit Baru Tanam (0-15 HST)',
    triggerFactors: ['Genangan air terlalu dalam (> 5 cm) pada 1-2 minggu pertama setelah tanam.'],
    monitoringMethod: 'Amati keberadaan kelompok telur merah muda di pematang/tiang dan bibit yang mengapung.',
    economicThreshold: 'Ditemukan 1 ekor keong mas dewasa per m² pada tanaman berumur < 15 HST.',
    culturalControl: 'Tanam bibit umur agak tua (> 20 hari HSS) dengan batang lebih keras, atur air macak-macak (1-2 cm) agar keong tidak aktif bergerak.',
    mechanicalControl: 'Pungut keong dan hancurkan kelompok telur merah muda, buat parit cacing (carem) sedalam 10 cm keliling petak sebagai perangkap.',
    biologicalControl: 'Gembalakan bebek ke petak sawah setelah olah tanah pratanam untuk memangsa anak keong.',
    chemicalControl: 'Moluskisida berbahan aktif niklosamida bila populasi sangat tinggi saat air sulit dikeringkan.',
    activeIngredients: ['Niklosamida Etanolamin', 'Fentin Asetat'],
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

export const SEED_NATURAL_ENEMIES: NaturalEnemy[] = [
  {
    id: 'enemy-laba-serigala',
    name: 'Laba-laba Serigala Pemburu',
    scientificName: 'Pardosa pseudoannulata',
    type: 'PREDATOR',
    targetOptIds: ['opt-wereng-coklat', 'opt-penggerek-kuning'],
    attackedStages: ['Nimfa', 'Imago/Dewasa'],
    habitat: 'Pangkal batang padi dan permukaan air sawah.',
    conservationNotes: 'Pertahankan petak sawah dari aplikasi insektisida semprotan langsung ke pangkal batang jika populasi laba-laba tinggi (1 ekor/rumpun).',
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'enemy-kumbang-kubah',
    name: 'Kumbang Kubah Bergaris',
    scientificName: 'Micraspis crocea',
    type: 'PREDATOR',
    targetOptIds: ['opt-wereng-coklat', 'opt-walang-sangit'],
    attackedStages: ['Telur', 'Nimfa muda'],
    habitat: 'Kanopi daun bagian atas dan malai.',
    conservationNotes: 'Tanam tanaman refugia berbunga kuning (kenikir, bunga tahi ayam) di pematang sawah sebagai sumber nektar alternatif.',
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'enemy-trichogramma',
    name: 'Tawon Parasitoid Telur',
    scientificName: 'Trichogramma japonicum',
    type: 'PARASITOID',
    targetOptIds: ['opt-penggerek-kuning'],
    attackedStages: ['Telur'],
    habitat: 'Bebas terbang di kanopi persawahan.',
    conservationNotes: 'Sangat rentan terhadap kabut insektisida kimia; hindari penyemprotan rutin terjadwal.',
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'enemy-kepik-mirid',
    name: 'Kepik Mirid Pemangsa Telur',
    scientificName: 'Cyrtorhinus lividipennis',
    type: 'PREDATOR',
    targetOptIds: ['opt-wereng-coklat'],
    attackedStages: ['Telur', 'Nimfa muda'],
    habitat: 'Pangkal batang dan pelepah daun padi.',
    conservationNotes: 'Kepik ini sangat efektif memangsa telur wereng di dalam jaringan pelepah.',
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'enemy-burung-hantu',
    name: 'Burung Hantu Tyto alba',
    scientificName: 'Tyto alba javanica',
    type: 'PREDATOR',
    targetOptIds: ['opt-tikus-sawah'],
    attackedStages: ['Dewasa', 'Anak Tikus'],
    habitat: 'Kandang / Rumah Burung Hantu (Rubuha) di tengah hamparan sawah.',
    conservationNotes: 'Satu pasang Tyto alba mampu memangsa 2-5 ekor tikus per malam; lindungi sarang dari perburuan liar.',
    referenceId: 'ref-bbpopt-tikus-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'enemy-kumbang-tomcat',
    name: 'Kumbang Jelajah / Tomcat',
    scientificName: 'Paederus fuscipes',
    type: 'PREDATOR',
    targetOptIds: ['opt-wereng-coklat', 'opt-penggerek-kuning'],
    attackedStages: ['Nimfa', 'Larva kecil'],
    habitat: 'Permukaan tanah dan tajuk tanaman padi.',
    conservationNotes: 'Predator generalis yang sangat rakus memangsa wereng muda.',
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

export const SEED_KNOWLEDGE_ARTICLES: KnowledgeArticle[] = [
  {
    id: 'art-pupuk-berimbang',
    category: 'FERTILIZATION',
    title: 'Prinsip Dasar Pemupukan Padi Berimbang (5T)',
    summary: 'Panduan pemupukan padi yang tepat jenis, tepat dosis, tepat waktu, tepat cara, dan tepat mutu berdasarkan kaidah Balittanah Kementan RI.',
    content: `Pemupukan berimbang adalah pemberian pupuk ke dalam tanah dengan jumlah dan jenis hara yang sesuai dengan tingkat kesuburan tanah dan kebutuhan fisiologis tanaman.

Prinsip 5 Tepat:
1. **Tepat Jenis**: Memberikan pupuk sesuai kekurangan unsur hara tanah (N, P, K, S, dll).
2. **Tepat Dosis**: Menyesuaikan target hasil dan kelas kesuburan tanah, menghindari kelebihan Urea yang memicu tanaman sukulen, mudah rebah, dan rentan serangan hama.
3. **Tepat Waktu**: Diberikan pada fase serapan aktif tanaman (Pupuk Dasar 0-7 HST, Anakan Aktif 21-25 HST, dan Primordia/Bunting 40-45 HST).
4. **Tepat Cara**: Ditabur merata saat kondisi air macak-macak (tidak tergenang dalam agar pupuk tidak larut terbuang ke saluran pembuangan).
5. **Tepat Mutu**: Menggunakan pupuk resmi berlabel SNI dan nomor pendaftaran Kementan yang sah.`,
    tags: ['Pemupukan', 'Hara', 'Urea', 'NPK', 'Dasar', 'Balittanah'],
    referenceId: 'ref-pupuk-kementan-2021',
    verifiedDate: '2026-01-15T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'art-pht-dasar',
    category: 'PEST_DISEASE',
    title: 'Prinsip Pengendalian Hama Terpadu (PHT) pada Padi Sawah',
    summary: 'Mengenal konsep 4 pilar PHT: budidaya tanaman sehat, pelestarian musuh alami, pengamatan mingguan rutin, dan petani sebagai ahli PHT di lahannya.',
    content: `Pengendalian Hama Terpadu (PHT) bukan berarti tidak boleh menyemprot pestisida kimia, melainkan menempatkan pestisida kimia sebagai jalan terakhir bila populasi hama melampaui ambang kendali ekonomi.

4 Pilar Utama PHT Padi:
1. **Budidaya Tanaman Sehat**: Benih unggul bersertifikat, jarak tanam teratur (Jajar Legowo), pemupukan berimbang spesifik lokasi, dan pengairan berselang.
2. **Pelestarian & Pemanfaatan Musuh Alami**: Menjaga predator alami (laba-laba, kumbang kubah, kepik mirid, parasitoid telur) dengan menanam tanaman berbunga (refugia) di pematang.
3. **Pengamatan Mingguan Teratur**: Petani memantau petak sawahnya minimal seminggu sekali untuk mengetahui rasio hama dan musuh alami secara dini.
4. **Petani Sebagai Ahli PHT**: Petani mengambil keputusan pengendalian secara mandiri berdasarkan fakta lapang nyata.`,
    tags: ['PHT', 'OPT', 'Musuh Alami', 'Pengamatan', 'Ditlin'],
    referenceId: 'ref-pht-padi-2019',
    verifiedDate: '2026-01-15T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'art-jajar-legowo',
    category: 'CULTIVATION',
    title: 'Sistem Tanam Jajar Legowo 2:1 untuk Padi Sawah',
    summary: 'Meningkatkan populasi rumpun hingga 33% per hektar dan memaksimalkan efek tanaman pinggir yang lebih produktif.',
    content: `Sistem tanam Jajar Legowo 2:1 adalah cara tanam berselang antara dua baris tanaman dan satu baris kosong dengan jarak antar baris 20-25 cm dan jarak dalam baris 10-12.5 cm.

Keunggulan Jajar Legowo 2:1:
1. **Peningkatan Populasi**: Menambah populasi rumpun tanaman hingga 213.300 rumpun/ha dibandingkan tegel 25x25 cm (160.000 rumpun/ha).
2. **Efek Tanaman Pinggir (Border Effect)**: Seluruh barisan tanaman mendapat sirkulasi udara dan radiasi sinar matahari optimal sehingga fotosintesis lebih tinggi.
3. **Kemudahan Pemeliharaan**: Lorong kosong memudahkan pemupukan susulan, penyiangan gulma, dan penyemprotan OPT.
4. **Menekan Kelembapan Mikro**: Mengurangi risiko perkembangan penyakit jamur Blas dan Hawar Daun Bakteri.`,
    tags: ['Budidaya', 'Jajar Legowo', 'Tanam', 'Populasi', 'BBPadi'],
    referenceId: 'ref-litbang-padi-2020',
    verifiedDate: '2026-01-20T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'art-pengairan-berselang',
    category: 'IRRIGATION',
    title: 'Teknik Pengairan Berselang (Intermittent / AWD) pada Sawah',
    summary: 'Pengaturan air sawah tergenang dan kering secara bergantian untuk menghemat air 20-30%, mencegah rebah, dan merangsang perakaran dalam.',
    content: `Pengairan berselang (Alternate Wetting and Drying / AWD) adalah teknik pengaturan air kondisi tergenang dan kering secara berkala sesuai kebutuhan fase pertumbuhan padi.

Jadwal Pelaksanaan Pengairan:
- **0-7 HST (Adaptasi)**: Tergenang dangkal (1-2 cm) untuk mencegah bibit hanyut dan menekan gulma awal.
- **8-35 HST (Anakan Aktif)**: Terapkan pengairan berselang; biarkan petak sawah surut hingga tanah sedikit retak rambut (retak halus), lalu airi kembali setinggi 3 cm.
- **40-65 HST (Bunting - Berbunga Penuh)**: Wajib tergenang dangkal (3-5 cm) karena tanaman sangat sensitif terhadap kekurangan air saat pembentukan malai dan sari.
- **70-85 HST (Pengisian Bulir)**: Pengairan berselang kembali (kondisi macak-macak).
- **10-14 Hari Sebelum Panen**: Keringkan petak sawah secara total untuk mematangkan gabah serempak dan mempermudah panen.`,
    tags: ['Irigasi', 'Air Berselang', 'AWD', 'Macak-Macak', 'IRRI'],
    referenceId: 'ref-irri-rice-knowledge',
    verifiedDate: '2026-01-20T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'art-manajemen-persemaian',
    category: 'CULTIVATION',
    title: 'Panduan Persemaian Padi Sehat & Pencegahan Dini OPT',
    summary: 'Langkah kunci seleksi benih bernas dengan larutan garam, perlakuan benih (seed treatment), dan pemeliharaan bibit prima.',
    content: `Persemaian adalah fondasi utama keberhasilan budidaya padi. Bibit yang sehat, kokoh, dan bebas patogen akan tumbuh cepat setelah pindah tanam.

Tahapan Persemaian Prima:
1. **Uji Benih Bernas (Larutan Garam)**: Masukkan telur ayam mentah ke dalam air, tambahkan garam dapur sampai telur terapung di permukaan. Masukkan benih padi; gunakan hanya benih yang tenggelam di dasar wadah, lalu bilas air bersih.
2. **Perlakuan Benih (Seed Treatment)**: Rendam benih bernas selama 24 jam dengan agens hayati Paenibacillus polymyxa atau fungisida perlakuan benih untuk membunuh spora jamur bawaan.
3. **Pemeraman**: Peram benih di karung goni basah selama 24-48 jam sampai titik tumbuh akar (radikula) muncul 1-2 mm.
4. **Bedengan Persemaian**: Buat bedengan lebar 1-1.2 m, tabur pupuk organik matang merata. Tabur benih dengan kerapatan tidak terlalu padat (25-30 gram benih/m²).
5. **Umur Pindah Tanam**: Bibit dipindahtanamkan pada umur 15-21 hari setelah sebar (HSS) dengan daun 3-4 helai.`,
    tags: ['Persemaian', 'Bibit', 'Benih Bernas', 'Seedbed', 'BBPadi'],
    referenceId: 'ref-litbang-padi-2020',
    verifiedDate: '2026-01-22T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'art-tikus-tbs-manajemen',
    category: 'PEST_DISEASE',
    title: 'Teknologi Pengendalian Hama Tikus Berbasis LTBS & TBS',
    summary: 'Metode pengendalian tikus sawah ramah lingkungan dengan sistem bubu perangkap tanpa racun berbahaya.',
    content: `Tikus sawah (Rattus argentiventer) merupakan salah satu hama utama yang menyerang sejak awal musim tanam hingga panen.

Metode Pengendalian Terpadu:
1. **Gropyokan Massal Pratanam**: Dilakukan bersama seluruh kelompok tani saat pengolahan tanah awal sebelum tikus memasuki masa kawin.
2. **Linear Trap Barrier System (LTBS)**: Bentangan pagar plastik setinggi 50-60 cm sepanjang 100-200 meter di batas habitat tikus dengan bubu perangkap setiap 20 meter.
3. **Trap Barrier System (TBS)**: Petak tanaman perangkap berukuran 20x20 m yang ditanam 2-3 minggu lebih awal dari hamparan sekitarnya, dipagar plastik dengan bubu penangkap.
4. **Konservasi Burung Hantu Tyto alba**: Pemasangan Rumah Burung Hantu (Rubuha) untuk perkembangbiakan predator alami.
5. **Sanitasi Pematang**: Perkecil pematang sawah (< 30 cm) agar tikus tidak nyaman bersarang.`,
    tags: ['Tikus', 'TBS', 'LTBS', 'Tyto alba', 'BBPOPT'],
    referenceId: 'ref-bbpopt-tikus-2021',
    verifiedDate: '2026-01-22T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'art-panen-pasca-panen',
    category: 'HARVEST',
    title: 'Tanda Kematangan Optimal & Penanganan Panen Padi',
    summary: 'Mencegah kehilangan hasil saat panen dengan menentukan umur panen dan kadar air gabah yang tepat.',
    content: `Waktu panen yang tepat sangat menentukan mutu beras (rendemen beras kepala tinggi dan menekan beras patah).

Tanda Padi Siap Panen:
1. **Kuning Malai**: 90-95% bulir gabah pada malai telah menguning sempurna.
2. **Daun Bendera**: Daun bendera telah menguning atau mengering secara alami.
3. **Kadar Air**: Kadar air gabah ideal saat panen berada pada kisaran 21-24%.
4. **Pencegahan Kehilangan Hasil**: Gunakan alas terpal bersih saat perontokan manual atau gunakan Combine Harvester dengan setelan blower optimal.`,
    tags: ['Panen', 'Kadar Air', 'GKP', 'Rendemen', 'BBPadi'],
    referenceId: 'ref-litbang-padi-2020',
    verifiedDate: '2026-01-20T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];
