/**
 * HIKMAT TANI - Seed Data Awal & Pustaka Agronomi Terverifikasi
 * 
 * Standar Data:
 * - Sumber resmi dari BBPadi Sukamandi (Litbang Pertanian / BRIN), Ditlin Kementan RI, Balittanah, dan IRRI.
 * - Tanpa data fiktif atau mengarang rekomendasi agronomi.
 * - Format ID konsisten dan unik untuk mencegah duplikasi.
 */

import {
  Fertilizer,
  KnowledgeArticle,
  NaturalEnemy,
  Opt,
  Reference,
  RiceVariety,
} from '../types/index.ts';

export const SEED_REFERENCES: Reference[] = [
  {
    id: 'ref-litbang-padi-2020',
    title: 'Petunjuk Teknis Budidaya Padi Sawah Irigasi Berorientasi IP 400',
    authorInstitution: 'Balai Besar Penelitian Tanaman Padi (BBPadi) Sukamandi - Badan Litbang Pertanian',
    publicationYear: 2020,
    sourceUrlOrBook: 'Buku Juknis BBPadi Sukamandi Kementan RI',
    regionApplicability: 'Nasional / Sawah Irigasi & Tadah Hujan',
    validationStatus: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ref-pht-padi-2019',
    title: 'Pedoman Pengendalian Hama Terpadu (PHT) Tanaman Padi',
    authorInstitution: 'Direktorat Perlindungan Tanaman Pangan, Ditjen Tanaman Pangan Kementan RI',
    publicationYear: 2019,
    sourceUrlOrBook: 'Buku Pedoman Ditlin Tanaman Pangan Jakarta',
    regionApplicability: 'Nasional',
    validationStatus: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ref-pupuk-kementan-2021',
    title: 'Rekomendasi Pemupukan N, P, dan K Spesifik Lokasi untuk Tanaman Padi Sawah',
    authorInstitution: 'Balai Penelitian Tanah (Balittanah) Bogor - Kementan RI',
    publicationYear: 2021,
    sourceUrlOrBook: 'Permentan Rekomendasi Pupuk N, P, K Spesifik Lokasi',
    regionApplicability: 'Nasional',
    validationStatus: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ref-irri-rice-knowledge',
    title: 'Rice Knowledge Bank - Alternate Wetting and Drying (AWD) & Integrated Pest Management',
    authorInstitution: 'International Rice Research Institute (IRRI) Los Baños',
    publicationYear: 2022,
    sourceUrlOrBook: 'IRRI Agronomy & Crop Management Compendium',
    regionApplicability: 'Asia Tenggara / Tropis',
    validationStatus: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ref-brin-varietas-2023',
    title: 'Deskripsi Varietas Unggul Baru Padi Sawah dan Profil Ketahanan Cekaman Biotik/Abiotik',
    authorInstitution: 'Pusat Riset Tanaman Pangan - Organisasi Riset Pertanian dan Pangan BRIN',
    publicationYear: 2023,
    sourceUrlOrBook: 'Katalog Varietas Unggul Padi BRIN',
    regionApplicability: 'Nasional',
    validationStatus: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ref-bbpopt-tikus-2021',
    title: 'Teknologi Pengendalian Hama Tikus Sawah Berbasis Trap Barrier System (TBS)',
    authorInstitution: 'Balai Besar Peramalan Organisme Pengganggu Tumbuhan (BBPOPT) Jatisari',
    publicationYear: 2021,
    sourceUrlOrBook: 'Jurnal Perlindungan Tanaman Pertanian BBPOPT',
    regionApplicability: 'Nasional',
    validationStatus: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ref-gulma-padi-2022',
    title: 'Pengenalan dan Pengelolaan Gulma Utama pada Ekosistem Sawah Irigasi',
    authorInstitution: 'Balai Besar Penelitian Tanaman Padi (BBPadi) & Ditlin Tanaman Pangan',
    publicationYear: 2022,
    sourceUrlOrBook: 'Buku Seri Perlindungan Tanaman Padi BBPadi',
    regionApplicability: 'Nasional',
    validationStatus: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ref-lapang-ip-padi-2025',
    title: 'Kajian Lapang Adaptasi Varietas Baru & Pengendalian Hayati Berbasis Kearifan Lokal',
    authorInstitution: 'Tim Pengkaji Budidaya Lapang & PPL Swadaya',
    publicationYear: 2025,
    sourceUrlOrBook: 'Laporan Kajian Lapang Dinamika Populasi & Uji Agroklimat',
    regionApplicability: 'Jawa Barat & Jawa Tengah',
    validationStatus: 'REVIEW',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

export const SEED_FERTILIZERS: Fertilizer[] = [
  {
    id: 'fert-urea',
    name: 'Urea (Prill/Granul)',
    type: 'INORGANIC_SINGLE',
    formula: '46-0-0',
    nutrientComposition: { N: 46 },
    aliases: ['Urea', 'Nitrogen', 'Pupuk Putih'],
    referenceId: 'ref-pupuk-kementan-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'fert-sp36',
    name: 'SP-36 (Super Phosphate)',
    type: 'INORGANIC_SINGLE',
    formula: '0-36-0 + 5S',
    nutrientComposition: { P2O5: 36, S: 5 },
    aliases: ['SP36', 'SP-36', 'Fosfat'],
    referenceId: 'ref-pupuk-kementan-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'fert-kcl',
    name: 'KCl (Kalium Klorida / MOP)',
    type: 'INORGANIC_SINGLE',
    formula: '0-0-60',
    nutrientComposition: { K2O: 60 },
    aliases: ['KCl', 'MOP', 'Pupuk Merah', 'Kalium'],
    referenceId: 'ref-pupuk-kementan-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'fert-za',
    name: 'ZA (Zwavelzure Amoniak)',
    type: 'INORGANIC_SINGLE',
    formula: '21-0-0 + 24S',
    nutrientComposition: { N: 21, S: 24 },
    aliases: ['ZA', 'Amonium Sulfat', 'Sulfur'],
    referenceId: 'ref-pupuk-kementan-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'fert-npk-ponska',
    name: 'NPK Phonska (15-15-15 + 10S)',
    type: 'INORGANIC_COMPOUND',
    formula: '15-15-15 + 10S',
    nutrientComposition: { N: 15, P2O5: 15, K2O: 15, S: 10 },
    aliases: ['Phonska', 'NPK Phonska', 'NPK 15-15-15'],
    referenceId: 'ref-pupuk-kementan-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'fert-npk-16-16-16',
    name: 'NPK Mutiara / Kujang (16-16-16)',
    type: 'INORGANIC_COMPOUND',
    formula: '16-16-16',
    nutrientComposition: { N: 16, P2O5: 16, K2O: 16 },
    aliases: ['NPK 16', 'NPK Biru', 'NPK Kujang 16'],
    referenceId: 'ref-pupuk-kementan-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'fert-kompos-kandang',
    name: 'Pupuk Kandang Sapi Matang / Kompos',
    type: 'ORGANIC',
    formula: 'Organik Terfermentasi Matang',
    nutrientComposition: { N: 1.5, P2O5: 1.0, K2O: 1.5, Ca: 0.8, Mg: 0.5 },
    aliases: ['Pukan', 'Pupuk Kandang', 'Kohe Sapi', 'Kompos Matang'],
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'fert-dolomit',
    name: 'Kapur Pertanian / Dolomit (CaCO3 + MgCO3)',
    type: 'INORGANIC_SINGLE',
    formula: 'CaMg(CO3)2',
    nutrientComposition: { Ca: 30, Mg: 18 },
    aliases: ['Dolomit', 'Kaptan', 'Kapur Pertanian'],
    referenceId: 'ref-pupuk-kementan-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

export const SEED_VARIETIES: RiceVariety[] = [
  {
    id: 'var-inpari-32',
    name: 'Inpari 32 HDB',
    aliases: ['Inpari 32', 'Ciherang Baru'],
    growthDurationDays: 120,
    potentialYieldKgHa: 8420,
    resistanceProfile: 'Tahan Hawar Daun Bakteri (HDB) strain III, IV, VIII; Agak tahan Blas',
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-ciherang',
    name: 'Ciherang',
    aliases: ['Ciherang Asli', 'IR64 Turunan'],
    growthDurationDays: 116,
    potentialYieldKgHa: 8500,
    resistanceProfile: 'Tahan Wereng Batang Coklat biotipe 2 dan 3; Agak tahan HDB strain III',
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-inpari-42',
    name: 'Inpari 42 Agritan GSR',
    aliases: ['Inpari 42', 'Green Super Rice'],
    growthDurationDays: 112,
    potentialYieldKgHa: 10580,
    resistanceProfile: 'Tahan Blas, Tahan HDB strain III, Toleran kekeringan/efisiensi hara',
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-mekongga',
    name: 'Mekongga',
    aliases: ['Mekongga Sukamandi'],
    growthDurationDays: 118,
    potentialYieldKgHa: 8400,
    resistanceProfile: 'Tahan Wereng Batang Coklat biotipe 2 dan 3; Agak tahan HDB strain IV',
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-situ-bagendit',
    name: 'Situ Bagendit',
    aliases: ['Bagendit', 'Padi Gogo Bagendit'],
    growthDurationDays: 110,
    potentialYieldKgHa: 6000,
    resistanceProfile: 'Sangat cocok untuk sawah tadah hujan & lahan kering (gogo); Toleran kekeringan',
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-sintanur',
    name: 'Sintanur',
    aliases: ['Sintanur Wangi', 'Padi Aromatik'],
    growthDurationDays: 115,
    potentialYieldKgHa: 7200,
    resistanceProfile: 'Beras pulen aromatik pandan wangi; Agak tahan HDB strain III',
    referenceId: 'ref-brin-varietas-2023',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-inpari-48-blas',
    name: 'Inpari 48 Blas',
    aliases: ['Inpari 48'],
    growthDurationDays: 115,
    potentialYieldKgHa: 9130,
    resistanceProfile: 'Tahan Blas Daun dan Leher ras 033, 073, 133; Tahan WBC biotipe 1, 2, 3',
    referenceId: 'ref-brin-varietas-2023',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-ir64',
    name: 'IR64',
    aliases: ['IR-64 Klasik'],
    growthDurationDays: 115,
    potentialYieldKgHa: 7000,
    resistanceProfile: 'Varietas tetua legendaris; Rasa nasi sangat pulen; Agak rentan wereng biotipe 3 baru',
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-ciherang',
    name: 'Ciherang',
    aliases: ['Ciherang Klasik'],
    growthDurationDays: 116,
    potentialYieldKgHa: 8500,
    resistanceProfile: 'Populer luas di Indonesia; Rasa nasi pulen; Tahan terhadap HDB strain III dan IV',
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-mekongga',
    name: 'Mekongga',
    aliases: ['Mekongga'],
    growthDurationDays: 118,
    potentialYieldKgHa: 8400,
    resistanceProfile: 'Nasi pulen enak; Tahan terhadap WBC biotipe 2 dan 3; Agak tahan HDB strain IV',
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-inpari-42-gsr',
    name: 'Inpari 42 Agritan GSR',
    aliases: ['Inpari 42', 'Green Super Rice'],
    growthDurationDays: 112,
    potentialYieldKgHa: 10580,
    resistanceProfile: 'Tipe Green Super Rice (hemat input); Tahan Blas ras 073 & 133; Tahan WBC biotipe 1 & 2',
    referenceId: 'ref-brin-varietas-2023',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-inpari-nutri-zinc',
    name: 'Inpari IR Nutri Zinc',
    aliases: ['Inpari Nutri Zinc', 'Padi Biofortifikasi Zn'],
    growthDurationDays: 115,
    potentialYieldKgHa: 9980,
    resistanceProfile: 'Kandungan Zn beras tinggi (~29.54 ppm); Tahan Blas ras 033; Tahan WBC biotipe 1 & 2',
    referenceId: 'ref-brin-varietas-2023',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'var-situbagendit',
    name: 'Situ Bagendit',
    aliases: ['Situ Bagendit', 'Padi Gogo Sawah'],
    growthDurationDays: 115,
    potentialYieldKgHa: 6000,
    resistanceProfile: 'Toleran kekeringan (amfibi untuk sawah tadah hujan dan gogo); Tahan Blas ras 033',
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

export const SEED_OPTS: Opt[] = [
  {
    id: 'opt-penggerek-kuning',
    commonName: 'Penggerek Batang Padi Kuning (PBPK)',
    scientificName: 'Scirpophaga incertulas',
    category: 'INSECT_PEST',
    aliases: ['Sundep', 'Beluk', 'Ulat Penggerek', 'Kaper'],
    symptoms: 'Fase vegetatif: pucuk tanaman mati/kering mudah dicabut bila ditarik (Sundep). Fase generatif: malai hampa keputihan tegak (Beluk).',
    lifeCycle: 'Telur (6-7 hari) -> Larva aktif (28-35 hari) -> Pupa di pangkal batang (6-9 hari) -> Ngengat kaper (4-5 hari). Total 40-55 hari.',
    hostPlants: ['Padi sawah', 'Padi liar (Oryza rufipogon)'],
    vulnerableStage: 'Vegetatif (Pembentukan Anakan) & Primordia/Bunting',
    triggerFactors: ['Pemupukan Urea/N berlebih tanpa imbangan K', 'Penanaman tidak serempak dalam satu hamparan', 'Lampu penerangan malam dekat petak sawah'],
    monitoringMethod: 'Amati rumpun contoh secara diagonal; hitung jumlah kelompok telur berbulu halus dan persentase anakan sundep/beluk.',
    economicThreshold: 'Rata-rata 1 kelompok telur per rumpun atau serangan sundep > 5% pada fase vegetatif awal.',
    culturalControl: 'Tanam serempak dalam hamparan minimal 10 ha, potong pucuk bibit saat pindah tanam, atur pemupukan N seimbang.',
    mechanicalControl: 'Kumpulkan dan musnahkan kelompok telur, pasang lampu perangkap (light trap) 40 watt di sudut sawah.',
    biologicalControl: 'Konservasi tawon parasitoid telur Trichogramma japonicum, Telenomus rowani, serta laba-laba pemburu.',
    chemicalControl: 'Aplikasi insektisida sistemik berbahan aktif terdaftar jika ambang pengendalian terlampaui.',
    activeIngredients: ['Klorantraniliprol', 'Dimehipo', 'Fipronil', 'Kartap Hidroklorida'],
    resistanceNotes: 'Hindari penggunaan bahan aktif golongan yang sama berturut-turut.',
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-wereng-coklat',
    commonName: 'Wereng Batang Coklat (WBC)',
    scientificName: 'Nilaparvata lugens',
    category: 'INSECT_PEST',
    aliases: ['Wereng Coklat', 'WBC', 'Hopperburn'],
    symptoms: 'Tanaman menguning, mengering cepat seperti terbakar melingkar dari tengah petak (Hopperburn); penular virus kerdil rumput & kerdil hampa.',
    lifeCycle: 'Telur (7-9 hari) -> Nimfa 5 instar (12-15 hari) -> Imago dewasa (18-20 hari).',
    hostPlants: ['Padi sawah'],
    vulnerableStage: 'Fase Anakan Maksimum hingga Pemasakan Bulir',
    triggerFactors: ['Penggunaan insektisida piretroid sintetik yang mematikan musuh alami', 'Aplikasi pupuk N dosis tinggi', 'Jarak tanam terlalu rapat tanpa lorong Legowo'],
    monitoringMethod: 'Periksa pangkal batang padi di bawah kanopi daun pada 20 rumpun sampel secara berkala setiap 5-7 hari.',
    economicThreshold: 'Kepadatan rata-rata >= 10 ekor per rumpun pada fase vegetatif, atau >= 20 ekor per rumpun pada fase bunting/generatif.',
    culturalControl: 'Tanam varietas tahan (Inpari 32, Inpari 48), gunakan sistem tanam Jajar Legowo 2:1, terapkan pengairan berselang (AWD).',
    mechanicalControl: 'Keringkan petak sawah selama 3-5 hari untuk menurunkan kelembapan mikro di pangkal rumpun.',
    biologicalControl: 'Laba-laba Pardosa pseudoannulata, kumbang Tomcat Paederus fuscipes, kepik Cyrtorhinus lividipennis, jamur Beauveria bassiana.',
    chemicalControl: 'Gunakan insektisida spesifik penghambat pertumbuhan (IGR) atau sistemik selektif bila populasi melampaui ambang ekonomi.',
    activeIngredients: ['Buprofezin', 'Pimetrozin', 'Triflumuron', 'Dinotefuran'],
    resistanceNotes: 'Hindari insektisida semprot spektrum luas yang dapat memicu ledakan resurgensi wereng.',
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-tikus-sawah',
    commonName: 'Tikus Sawah',
    scientificName: 'Rattus argentiventer',
    category: 'VERTEBRATE_PEST',
    aliases: ['Tikus', 'Hama Pengerat', 'Rattus'],
    symptoms: 'Batang padi terpotong miring membentuk sudut 45 derajat di bagian tengah petak; liang sarang aktif di pematang sawah dan tanggul saluran.',
    lifeCycle: 'Bunting 21 hari, melahirkan 6-12 anak per kelahiran, mampu berkembang biak 3 kali dalam satu musim tanam padi.',
    hostPlants: ['Padi', 'Jagung', 'Ubi jalar', 'Padi liar'],
    vulnerableStage: 'Semua fase, mulai dari Pesemaian, Anakan, hingga Fase Pengisian Bulir/Matang',
    triggerFactors: ['Pematang sawah terlalu lebar/tinggi (>30 cm) yang dijadikan sarang', 'Tanam tidak serempak', 'Sanitasi lingkungan persawahan kotor'],
    monitoringMethod: 'Amati jejak kaki, kotoran segar, liang aktif di pematang, dan persentase rumpun rusak terpotong miring.',
    economicThreshold: 'Ditemukan liang aktif baru atau kerusakan rumpun > 2% pada fase vegetatif awal.',
    culturalControl: 'Tanam serempak dalam hamparan, perkecil pematang sawah (< 30 cm), bersihkan semak dan gulma tanggul.',
    mechanicalControl: 'Gropyokan massal saat olah tanah (pratanam), pasang Sistem Bubu Perangkap (TBS / LTBS), emposan asap belerang pada liang aktif.',
    biologicalControl: 'Pemanfaatan musuh alami burung hantu Tyto alba dengan mendirikan Rumah Burung Hantu (Rubuha) 1 unit per 5 hektar.',
    chemicalControl: 'Umpan rodentisida antikoagulan terdaftar hanya pada awal musim di luar petakan.',
    activeIngredients: ['Kumatetralil', 'Bromadiolon', 'Fosfida Seng (Umpan Akut Terbatas)'],
    referenceId: 'ref-bbpopt-tikus-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-walang-sangit',
    commonName: 'Walang Sangit',
    scientificName: 'Leptocorisa oratorius',
    category: 'INSECT_PEST',
    aliases: ['Walang Sangit', 'Kepik Pengisap Bulir', 'Sangit'],
    symptoms: 'Bulir padi menjadi hampa atau berbintik coklat kehitaman (beras bernoda dan patah saat digiling); tercium bau sengit khas di sawah.',
    lifeCycle: 'Telur diletakkan berbaris pada daun (6-8 hari) -> Nimfa 5 instar (17-25 hari) -> Imago dewasa (50-60 hari).',
    hostPlants: ['Padi sawah', 'Rumput jampang (Digitaria ciliaris)', 'Rumput bebek (Echinochloa colona)'],
    vulnerableStage: 'Fase Masak Susu (Milk Stage) hingga Masak Kuning (Dough Stage)',
    triggerFactors: ['Keberadaan gulma rumput berbiji di pematang sawah', 'Penanaman bertahap tidak serentak'],
    monitoringMethod: 'Gunakan jaring ayun (sweep net) 20 kali ayunan diagonal di atas kanopi malai pada pagi (06.00-08.00) atau sore hari.',
    economicThreshold: 'Rata-rata 5 ekor walang sangit per 20 rumpun pada fase masak susu.',
    culturalControl: 'Pembersihan gulma inang rumput-rumputan di pematang sawah sebelum tanaman padi berbunga.',
    mechanicalControl: 'Gunakan perangkap berumpan bangkai kepiting/keong mas busuk yang digantung di tiang bambu sekitar pematang.',
    biologicalControl: 'Parasitoid telur Gryon nixoni dan jamur Beauveria bassiana.',
    chemicalControl: 'Penyemprotan insektisida berbahan aktif kontak pada pagi atau sore hari saat hama aktif bertengger di atas malai.',
    activeIngredients: ['BPMC (Fenobukarb)', 'MOPC', 'Karbosulfan', 'Deltametrin'],
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-hawar-daun-bakteri',
    commonName: 'Hawar Daun Bakteri (HDB / Kresek)',
    scientificName: 'Xanthomonas oryzae pv. oryzae',
    category: 'DISEASE',
    aliases: ['Kresek', 'HDB', 'Hawar Daun', 'Bacterial Blight'],
    symptoms: 'Bercak kuning kebasahan mulai dari pucuk atau tepi daun, meluas ke bawah menjadi kelabu keputihan berombak; daun layu mengering keriting.',
    lifeCycle: 'Bakteri bertahan pada sisa jerami sakit, gulma inang, dan benih; menular cepat lewat air irigasi dan luka gesekan daun.',
    hostPlants: ['Padi sawah', 'Gulma Leersia hexandra'],
    vulnerableStage: 'Semua fase, terutama Anakan Aktif (gejala Kresek) hingga Fase Bunting/Berbunga (gejala Hawar)',
    triggerFactors: ['Kelembapan tinggi (>85%), angin kencang disertai hujan lebat, dosis pupuk Urea/N berlebih tanpa pupuk K.'],
    monitoringMethod: 'Amati persentase luas permukaan daun yang bergejala pada petak sawah.',
    economicThreshold: 'Kerusakan daun > 10% pada fase anakan atau > 5% pada fase bunting.',
    culturalControl: 'Gunakan varietas tahan (Inpari 32, Inpari 48), hindari pemotongan daun bibit saat tanam, kurangi N, tambah pupuk K (KCl).',
    mechanicalControl: 'Sanitasi pematang dan singgang sisa panen yang terinfeksi.',
    biologicalControl: 'Aplikasi agens hayati bakteri antagonis Paenibacillus polymyxa atau Pseudomonas fluorescens.',
    chemicalControl: 'Bakterisida tembaga atau antibiotik pertanian terdaftar bila serangan meluas dan cuaca ekstrem.',
    activeIngredients: ['Tembaga Hidroksida', 'Tembaga Oksiklorida', 'Kasugamisin', 'Asam Oksolinik'],
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-blas-padi',
    commonName: 'Penyakit Blas Padi',
    scientificName: 'Pyricularia oryzae (Magnaporthe oryzae)',
    category: 'DISEASE',
    aliases: ['Blas Daun', 'Blas Leher', 'Patah Leher', 'Tengik', 'Rice Blast'],
    symptoms: 'Bercak berbentuk belah ketupat runcing di kedua ujung dengan pusat kelabu pada daun; leher tangkai malai membusuk kelabu kehitaman lalu patah (Blas Leher).',
    lifeCycle: 'Konidia jamur disebarkan lewat angin dan percikan embun pada malam hari yang dingin lembap (suhu 24-28°C).',
    hostPlants: ['Padi sawah', 'Padi gogo'],
    vulnerableStage: 'Vegetatif Awal (Blas Daun) & Fase Keluar Malai/Berbunga (Blas Leher)',
    triggerFactors: ['Dosis pupuk N sangat tinggi, tanah kekurangan silika (Si), kelembapan malam tinggi dengan kabut tebal berkepanjangan.'],
    monitoringMethod: 'Periksa daun muda bagian atas dan tangkai leher malai pada 20 rumpun sampel.',
    economicThreshold: 'Ditemukan bercak belah ketupat aktif pada daun bendera atau tanda awal infeksi pada leher malai saat bunting akhir.',
    culturalControl: 'Perlakuan benih (seed treatment), jarak tanam teratur (Jajar Legowo 2:1), pergiliran varietas, pemberian pupuk silika.',
    mechanicalControl: 'Eradikasi rumpun terinfeksi parah di persemaian sebelum pindah tanam.',
    biologicalControl: 'Pemanfaatan agens hayati jamur Trichoderma harzianum atau Trichoderma viride.',
    chemicalControl: 'Fungisida sistemik spesifik berbahan aktif terdaftar saat bunting tua dan saat keluar malai 5-10%.',
    activeIngredients: ['Trisiklazol', 'Isoprotiolan', 'Azoksistrobin', 'Difenokonazol', 'Tebukonazol'],
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-penyakit-tungro',
    commonName: 'Penyakit Tungro Padi',
    scientificName: 'Rice Tungro Bacilliform Virus (RTBV) & Rice Tungro Spherical Virus (RTSV)',
    category: 'DISEASE',
    aliases: ['Tungro', 'Kerdil Kuning', 'Kerdil Oranye', 'Mentek'],
    symptoms: 'Tanaman kerdil nyata, jumlah anakan sedikit, daun muda berwarna kuning jingga/oranye dari ujung memanjang ke bawah, malai keluar tidak sempurna dan hampa.',
    lifeCycle: 'Virus ditularkan oleh serangga vektor Wereng Daun Hijau (Nephotettix virescens) secara semi-persisten.',
    hostPlants: ['Padi sawah', 'Padi liar'],
    vulnerableStage: 'Pesemaian hingga Fase Anakan Aktif (0-30 HST)',
    triggerFactors: ['Populasi wereng hijau tinggi di persemaian, tanam tidak serempak dalam hamparan luas.'],
    monitoringMethod: 'Pantau keberadaan wereng hijau di pesemaian dan gejala daun oranye kekuningan pada rumpun muda.',
    economicThreshold: 'Ditemukan 1 tanaman bergejala tungro per 100 rumpun pada fase sebelum 30 HST.',
    culturalControl: 'Tanam serempak dalam hamparan, pergiliran varietas tahan tungro (Inpari 36, Inpari 37), eradikasi singgang sumber virus.',
    mechanicalControl: 'Cabut dan benamkan segera tanaman kerdil bergejala tungro agar tidak menular.',
    biologicalControl: 'Konservasi laba-laba predator dan pemangsa wereng hijau.',
    chemicalControl: 'Pengendalian ditujukan kepada serangga vektor (Wereng Hijau) dengan insektisida sistemik bila populasi tinggi di persemaian.',
    activeIngredients: ['Imidakloprid', 'Tiametoksam', 'Dimehipo'],
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-keong-mas',
    commonName: 'Keong Mas',
    scientificName: 'Pomacea canaliculata',
    category: 'MOLLUSC_PEST',
    aliases: ['Keong Mas', 'Siput Murbai', 'Siput Murbei'],
    symptoms: 'Batang dan helaian daun bibit padi muda terpotong pangkalnya dan mengapung di permukaan air; rumpun di persemaian atau sawah baru habis.',
    lifeCycle: 'Telur berwarna merah muda diletakkan berkelompok di atas permukaan air (7-14 hari) -> Anak keong rakus -> Dewasa (usia hidup 2-3 tahun).',
    hostPlants: ['Bibit padi muda (0-15 HST)', 'Kangkung', 'Eceng gondok'],
    vulnerableStage: 'Pesemaian & Fase Bibit Baru Tanam (0-15 HST)',
    triggerFactors: ['Genangan air terlalu dalam (> 5 cm) pada 1-2 minggu pertama setelah tanam.'],
    monitoringMethod: 'Amati keberadaan kelompok telur merah muda di pematang/tiang dan bibit yang mengapung.',
    economicThreshold: 'Ditemukan 1 ekor keong mas dewasa per m² pada tanaman berumur < 15 HST.',
    culturalControl: 'Tanam bibit umur agak tua (> 20 hari HSS) dengan batang lebih keras, atur air macak-macak (1-2 cm) agar keong tidak aktif bergerak.',
    mechanicalControl: 'Pungut keong dan hancurkan kelompok telur merah muda, buat parit cacing (carem) sedalam 10 cm keliling petak sebagai perangkap.',
    biologicalControl: 'Gembalakan bebek ke petak sawah setelah olah tanah pratanam untuk memangsa anak keong.',
    chemicalControl: 'Moluskisida berbahan aktif niklosamida bila populasi sangat tinggi saat air sulit dikeringkan.',
    activeIngredients: ['Niklosamida Etanolamin', 'Fentin Asetat'],
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-wereng-daun-hijau',
    commonName: 'Wereng Daun Hijau (WDH)',
    scientificName: 'Nephotettix virescens',
    category: 'INSECT_PEST',
    aliases: ['Wereng Hijau', 'WDH', 'Vektor Tungro'],
    symptoms: 'Daun menguning dari pucuk; merupakan vektor utama penular virus Tungro (RTBV/RTSV) yang menyebabkan tanaman kerdil dan daun berwarna oranye.',
    lifeCycle: 'Telur (6-8 hari) -> Nimfa 5 instar (12-19 hari) -> Dewasa (20-30 hari).',
    hostPlants: ['Padi sawah', 'Rumput teki', 'Padi liar'],
    vulnerableStage: 'Pesemaian hingga Vegetatif Aktif (0-35 HST)',
    triggerFactors: ['Tanam tidak serentak dalam hamparan luas', 'Populasi singgang sisa panen yang terinfeksi virus'],
    monitoringMethod: 'Gunakan jaring ayun di persemaian dan pertanaman muda pada pagi hari.',
    economicThreshold: 'Ditemukan > 5 ekor per ayunan di daerah endemis tungro, atau > 10 ekor di daerah non-endemis.',
    culturalControl: 'Tanam varietas tahan tungro dan wereng hijau, rotasi varietas, sanitasi singgang.',
    mechanicalControl: 'Pemasangan perangkap lampu kuning/putih.',
    biologicalControl: 'Laba-laba Pardosa pseudoannulata, kepik Cyrtorhinus lividipennis.',
    chemicalControl: 'Insektisida sistemik berbahan aktif terdaftar jika populasi melewati ambang kendali.',
    activeIngredients: ['Imidakloprid', 'Tiametoksam', 'Dimehipo'],
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-wereng-punggung-putih',
    commonName: 'Wereng Punggung Putih (WPP)',
    scientificName: 'Sogatella furcifera',
    category: 'INSECT_PEST',
    aliases: ['Wereng Punggung Putih', 'WPP'],
    symptoms: 'Daun padi menguning kecoklatan akibat cairan sel dihisap; pada serangan berat menyebabkan gejala hopperburn mirip wereng coklat.',
    lifeCycle: 'Telur (6-7 hari) -> Nimfa (12-15 hari) -> Imago dewasa (15-20 hari). Terdapat tanda garis putih memanjang di punggungnya.',
    hostPlants: ['Padi sawah', 'Jagung', 'Rumput-rumputan'],
    vulnerableStage: 'Vegetatif Awal hingga Anakan Maksimum (10-45 HST)',
    triggerFactors: ['Aplikasi pupuk nitrogen tinggi', 'Kondisi cuaca lembap hangat pada awal musim hujan'],
    monitoringMethod: 'Amati bagian pangkal hingga tengah rumpun padi secara acak.',
    economicThreshold: 'Kepadatan rata-rata >= 10 ekor per rumpun pada fase anakan.',
    culturalControl: 'Tanam jajar legowo, pergiliran varietas, pengairan berselang (AWD).',
    mechanicalControl: 'Pengeringan sawah 3-5 hari.',
    biologicalControl: 'Kepik mirid, laba-laba pemburu, jamur entomopatogen Beauveria bassiana.',
    chemicalControl: 'Insektisida selektif bila ambang ekonomi tercapai.',
    activeIngredients: ['Pimetrozin', 'Buprofezin', 'Dinotefuran'],
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-hama-putih-palsu',
    commonName: 'Hama Putih Palsu (Pelipat Daun)',
    scientificName: 'Cnaphalocrocis medinalis',
    category: 'INSECT_PEST',
    aliases: ['Hama Putih Palsu', 'HPP', 'Ulat Penggulung Daun', 'Leaf Folder'],
    symptoms: 'Daun terlipat memanjang dan bagian dalam daun terkikis putih transparan; fotosintesis terhambat.',
    lifeCycle: 'Telur (3-4 hari) -> Larva hijau transparan aktif melipat daun (15-25 hari) -> Pupa (6-8 hari) -> Ngengat kaper kecil coklat keemasan.',
    hostPlants: ['Padi sawah', 'Rumput jajagoan'],
    vulnerableStage: 'Fase Anakan Maksimum hingga Primordia / Bunting',
    triggerFactors: ['Pemupukan Urea/N sangat tinggi sehingga daun menjadi sangat sukulen dan lebat'],
    monitoringMethod: 'Hitung persentase daun terlipat putih pada 20 rumpun sampel.',
    economicThreshold: 'Kerusakan daun > 15% pada fase vegetatif atau > 5% pada daun bendera fase generatif.',
    culturalControl: 'Pemupukan N seimbang dengan K, bersihkan gulma inang di pematang.',
    mechanicalControl: 'Gunakan sapu lidi atau ranting untuk membuka gulungan daun saat serangan ringan.',
    biologicalControl: 'Tawon parasitoid Trichogramma dan laba-laba kanopi.',
    chemicalControl: 'Insektisida berbahan aktif klorantraniliprol atau dimehipo.',
    activeIngredients: ['Klorantraniliprol', 'Emamektin Benzoat', 'Dimehipo', 'Kartap'],
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-ulat-grayak',
    commonName: 'Ulat Grayak / Ulat Tentara',
    scientificName: 'Spodoptera litura / Spodoptera mauritia',
    category: 'INSECT_PEST',
    aliases: ['Ulat Grayak', 'Armyworm', 'Ulat Pemakan Daun'],
    symptoms: 'Daun bibit dan tanaman muda rompeng dimakan bergerombol dari pinggir hingga hanya tersisa tulang daun utama; serangan cepat dalam semalam.',
    lifeCycle: 'Telur tertutup bulu halus (3-5 hari) -> Larva ulat rakus (15-20 hari) -> Pupa di dalam tanah (7-10 hari) -> Ngengat malam.',
    hostPlants: ['Padi sawah', 'Jagung', 'Kedelai', 'Sayuran'],
    vulnerableStage: 'Pesemaian & Vegetatif Awal (0-20 HST)',
    triggerFactors: ['Musim peralihan (pancaroba)', 'Kondisi kering diikuti hujan sporadis'],
    monitoringMethod: 'Periksa kelompok telur berbulu halus di daun dan daun yang berlubang/rompeng pada malam atau pagi hari.',
    economicThreshold: 'Kerusakan daun bibit > 10% atau rata-rata 1 kelompok ulat per rumpun di persemaian.',
    culturalControl: 'Genangi petak persemaian sementara untuk menenggelamkan ulat ke permukaan air.',
    mechanicalControl: 'Kumpulkan dan musnahkan kelompok telur dan ulat instar awal.',
    biologicalControl: 'Virus Spodoptera litura Nucleopolyhedrovirus (SlNPV), jamur Metarhizium anisopliae.',
    chemicalControl: 'Insektisida kontak dan lambung yang diaplikasikan pada sore hari saat ulat aktif keluar.',
    activeIngredients: ['Klorantraniliprol', 'Emamektin Benzoat', 'Deltametrin', 'Klorfenapir'],
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-orong-orong',
    commonName: 'Orong-orong / Anjing Tanah',
    scientificName: 'Gryllotalpa orientalis',
    category: 'INSECT_PEST',
    aliases: ['Orong-orong', 'Gangsir', 'Anjing Tanah', 'Mole Cricket'],
    symptoms: 'Perakaran bibit di persemaian atau tanaman baru tanam terpotong di bawah permukaan tanah; bibit layu dan mengapung/tumbang.',
    lifeCycle: 'Telur di lorong tanah -> Nimfa liang tanah -> Imago dewasa bersayap liang (usia hidup 6-12 bulan).',
    hostPlants: ['Akar bibit padi', 'Benih yang baru disebar di persemaian'],
    vulnerableStage: 'Pesemaian & Fase Bibit 1-10 HST (terutama saat tanah macak-macak)',
    triggerFactors: ['Kondisi sawah becek/kering tanpa genangan air saat awal tanam'],
    monitoringMethod: 'Amati lorong tanah timbul di bedengan persemaian dan bibit yang roboh terkikis akar.',
    economicThreshold: 'Terdapat kerusakan perakaran > 5% pada bedengan persemaian.',
    culturalControl: 'Genangi petak persemaian atau sawah setinggi 3-5 cm agar orong-orong keluar dari liang tanah.',
    mechanicalControl: 'Ratakan dan padatkan permukaan tanah bedengan.',
    biologicalControl: 'Katak sawah, burung kuntul/blekok, dan jamur Beauveria.',
    chemicalControl: 'Umpan beracun sekam/dedak atau insektisida butiran berizin.',
    activeIngredients: ['Karbofuran (terbatas)', 'Fipronil butiran'],
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-lalat-bibit',
    commonName: 'Lalat Bibit Padi',
    scientificName: 'Atherigona oryzae',
    category: 'INSECT_PEST',
    aliases: ['Lalat Bibit', 'Shoot Fly', 'Ulat Lalat Bibit'],
    symptoms: 'Pucuk bibit padi berlubang dan menguning layu lalu membusuk (dead heart pada fase bibit); mirip sundep tapi terjadi pada fase sangat muda.',
    lifeCycle: 'Telur putih lonjong di bawah daun (2-3 hari) -> Larva belatung bor pucuk (8-12 hari) -> Pupa di pangkal tanaman (7 hari) -> Lalat kecil.',
    hostPlants: ['Bibit padi muda', 'Jagung', 'Sorgum'],
    vulnerableStage: 'Pesemaian & Tanaman Muda (0-14 HST)',
    triggerFactors: ['Penanaman terlambat di akhir musim tanam atau sawah yang kekeringan'],
    monitoringMethod: 'Periksa bibit di persemaian apakah ada telur putih di balik daun atau pucuk layu.',
    economicThreshold: 'Rata-rata > 5% bibit mengalami pucuk layu busuk di pesemaian.',
    culturalControl: 'Tanam serempak, hindari menanam bibit terlalu muda di daerah endemis lalat bibit.',
    mechanicalControl: 'Tutup persemaian dengan kain kasa/kelambu transparan (nursery net).',
    biologicalControl: 'Parasitoid famili Eulophidae dan Braconidae.',
    chemicalControl: 'Perlakuan benih (seed dressing) dengan insektisida sistemik sebelum sebar.',
    activeIngredients: ['Tiametoksam', 'Imidakloprid', 'Dimehipo'],
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-kepinding-tanah',
    commonName: 'Kepinding Tanah (Black Bug)',
    scientificName: 'Scotinophara coarctata',
    category: 'INSECT_PEST',
    aliases: ['Kepinding Tanah', 'Kepik Hitam Sawah', 'Malayan Black Bug'],
    symptoms: 'Tanaman kerdil, daun menguning kemerahan, pangkal batang berlubang bintik coklat kehitaman; pada malam hari mengeluarkan bau busuk menyengat.',
    lifeCycle: 'Telur merah muda berbaris di pangkal batang (4-7 hari) -> Nimfa (25-30 hari) -> Imago hitam mengkilap (tahan hidup berbulan-bulan di retakan tanah).',
    hostPlants: ['Padi sawah', 'Rumput teki', 'Padi liar'],
    vulnerableStage: 'Fase Anakan Aktif hingga Bunting Tua',
    triggerFactors: ['Sawah tergenang terus menerus di malam hari dekat lampu jalan; penumpukan jerami basah'],
    monitoringMethod: 'Amati pangkal rumpun padi dekat permukaan air terutama saat bulan purnama.',
    economicThreshold: 'Rata-rata 5-10 ekor per rumpun pada fase bunting.',
    culturalControl: 'Sanitasi sisa jerami dan singgang, pengeringan berselang petak sawah.',
    mechanicalControl: 'Pasang lampu perangkap (light trap) 40 watt di sudut pematang malam hari.',
    biologicalControl: 'Bebek gembala saat olah tanah, jamur Metarhizium anisopliae.',
    chemicalControl: 'Aplikasi insektisida semprot diarahkan langsung ke pangkal batang dekat air.',
    activeIngredients: ['BPMC (Fenobukarb)', 'Dimehipo', 'Klorantraniliprol'],
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-burung-pipit',
    commonName: 'Burung Pipit / Burung Bondol',
    scientificName: 'Lonchura sp. (Lonchura striata, Lonchura punctulata)',
    category: 'VERTEBRATE_PEST',
    aliases: ['Burung Pipit', 'Burung Emprit', 'Burung Bondol', 'Hama Burung'],
    symptoms: 'Bulir padi pada malai pecah terhisap pada fase masak susu dan rontok/habis saat masak kuning; malai tersisa tangkai kosong melengkung.',
    lifeCycle: 'Berkembang biak di pohon sekitar sawah; terbang berkelompok puluhan hingga ratusan ekor pagi (06.00-09.00) dan sore (15.00-17.30).',
    hostPlants: ['Padi sawah', 'Padi gogo', 'Sorgum', 'Rumput berbiji'],
    vulnerableStage: 'Fase Masak Susu (Milk Stage) hingga Menjelang Panen',
    triggerFactors: ['Tanam tidak serempak sehingga petak yang matang duluan menjadi sasaran tunggal burung'],
    monitoringMethod: 'Amati kawanan burung yang hinggap di petak malai saat fajar dan senja.',
    economicThreshold: 'Kerusakan malai > 2% pada fase masak susu.',
    culturalControl: 'Tanam serempak dalam hamparan luas minimal 20 ha agar serangan terbagi rata.',
    mechanicalControl: 'Pasang jaring pelindung burung (bird net), orang-orangan sawah bergerak, kincir angin kaleng berbunyi, tali kresek warna mengkilap.',
    biologicalControl: 'Burung pemangsa alami (Alap-alap / Elang tikus).',
    chemicalControl: 'Tidak direkomendasikan racun burung (melanggar konservasi lingkungan). Gunakan repellent pengusir aroma.',
    activeIngredients: ['Repellent Minyak Atsiri / Ekstrak Nabati'],
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-busuk-batang',
    commonName: 'Penyakit Busuk Batang (Stem Rot)',
    scientificName: 'Magnaporthe salvinii (Sclerotium oryzae)',
    category: 'DISEASE',
    aliases: ['Busuk Batang', 'Stem Rot', 'Rebah Batang Jamur'],
    symptoms: 'Bercak hitam kebasahan pada pelepah dekat permukaan air, menjalar ke batang dalam; batang membusuk, berongga, dan mudah rebah sebelum panen.',
    lifeCycle: 'Sklerosia hitam jamur bertahan di dalam tanah dan jerami sisa panen; mengapung saat penggenangan sawah dan menginfeksi pangkal batang.',
    hostPlants: ['Padi sawah'],
    vulnerableStage: 'Fase Pembentukan Anakan Maksimum hingga Pengisian Bulir',
    triggerFactors: ['Pupuk N dosis tinggi tanpa pupuk K', 'Genangan air sawah dalam berkepanjangan', 'Sisa jerami sakit tidak didekomposisi'],
    monitoringMethod: 'Periksa pelepah dan batang pada ketinggian permukaan air pada 20 rumpun sampel.',
    economicThreshold: 'Ditemukan bercak busuk batang pada > 5% rumpun fase bunting.',
    culturalControl: 'Pengeringan berselang (AWD), seimbangkan rasio N:K (tingkatkan KCl), bakar/dekomposisi jerami berpenyakit.',
    mechanicalControl: 'Pengeringan tanah intensif pasca panen.',
    biologicalControl: 'Agens hayati Trichoderma harzianum saat olah tanah.',
    chemicalControl: 'Fungisida berbahan aktif difenokonazol atau heksakonazol disemprotkan ke pangkal batang.',
    activeIngredients: ['Difenokonazol', 'Heksakonazol', 'Azoksistrobin', 'Validamisin'],
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-bercak-daun-coklat',
    commonName: 'Penyakit Bercak Daun Coklat (Brown Spot)',
    scientificName: 'Bipolaris oryzae (Helminthosporium oryzae)',
    category: 'DISEASE',
    aliases: ['Bercak Coklat', 'Brown Spot', 'Helminthosporiosis'],
    symptoms: 'Bercak bulat hingga oval berwarna coklat dengan lingkaran kuning di sekelilingnya pada helai daun dan gabah; gabah bernoda kusam hampa.',
    lifeCycle: 'Spora terbawa benih dan disebarkan lewat angin; menginfeksi terutama pada tanah miskin hara mikro (K, Si, Mn, Zn).',
    hostPlants: ['Padi sawah', 'Padi gogo'],
    vulnerableStage: 'Pesemaian hingga Fase Pengisian Bulir',
    triggerFactors: ['Tanah masam, defisiensi kalium dan silika, kekeringan pada tanah berpasir'],
    monitoringMethod: 'Amati daun bawah dan daun tengah terhadap bercak oval coklat.',
    economicThreshold: 'Kerusakan daun > 10% pada fase vegetatif akhir.',
    culturalControl: 'Perlakuan benih air hangat/fungisida, berikan pupuk kandang matang dan pupuk K serta Silika.',
    mechanicalControl: 'Sanitasi benih bernas larutan garam.',
    biologicalControl: 'Pseudomonas fluorescens dan Trichoderma.',
    chemicalControl: 'Fungisida sistemik semprot bila bercak menyebar ke daun bendera.',
    activeIngredients: ['Mankozeb', 'Propikonazol', 'Difenokonazol', 'Azoksistrobin'],
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-busuk-pelepah',
    commonName: 'Penyakit Busuk Pelepah Daun (Sheath Blight)',
    scientificName: 'Rhizoctonia solani',
    category: 'DISEASE',
    aliases: ['Hawar Pelepah Daun', 'Sheath Blight', 'Bercak Ular'],
    symptoms: 'Bercak oval kehijauan kelabu menyerupai kulit ular pada pelepah dekat muka air; menjalar ke atas hingga daun bendera dan malai.',
    lifeCycle: 'Sklerosia jamur bertahan bertahun-tahun di dalam tanah; mengapung dan menempel pada pelepah saat sawah diairi.',
    hostPlants: ['Padi sawah', 'Jagung', 'Kedelai'],
    vulnerableStage: 'Anakan Maksimum hingga Keluar Malai (35-65 HST)',
    triggerFactors: ['Jarak tanam terlalu rapat, kanopi rimbun akibat N berlebih, kelembapan mikro > 95%'],
    monitoringMethod: 'Periksa pelepah bagian bawah di sela-sela rumpun padat.',
    economicThreshold: 'Terdapat bercak pada > 5% rumpun pada fase bunting awal.',
    culturalControl: 'Gunakan jarak tanam Jajar Legowo 2:1, kurangi dosis Urea, aplikasi pupuk K seimbang.',
    mechanicalControl: 'Singkirkan sklerosia yang mengapung di saluran pembuangan saat olah tanah.',
    biologicalControl: 'Aplikasi Trichoderma dan Bacillus subtilis.',
    chemicalControl: 'Fungisida spesifik berbahan aktif validamisin atau difenokonazol.',
    activeIngredients: ['Validamisin A', 'Difenokonazol', 'Tebukonazol', 'Azoksistrobin'],
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-hawar-pelepah',
    commonName: 'Penyakit Hawar Pelepah / Busuk Bulir (Sheath Rot)',
    scientificName: 'Sarocladium oryzae',
    category: 'DISEASE',
    aliases: ['Sheath Rot', 'Busuk Malai Terbungkus', 'Hawar Pelepah Malai'],
    symptoms: 'Pelepah daun bendera membusuk kecoklatan sebelum malai keluar sempurna; malai tercekik di dalam pelepah daun bendera dan bulir menjadi hitam hampa.',
    lifeCycle: 'Jamur menginfeksi pelepah daun bendera melalui luka akibat serangga pengisap (wereng/kutu) atau gesekan.',
    hostPlants: ['Padi sawah'],
    vulnerableStage: 'Fase Bunting Tua hingga Bunting Akhir (Booting Stage)',
    triggerFactors: ['Tingginya populasi serangga perusak pelepah', 'Cuaca berkabut lembap saat fase bunting'],
    monitoringMethod: 'Periksa pelepah daun bendera pada 20 rumpun fase bunting.',
    economicThreshold: 'Ditemukan pelepah bendera membusuk pada > 2% rumpun.',
    culturalControl: 'Kendalikan serangga vektor/perusak pelepah, pemupukan N-P-K berimbang.',
    mechanicalControl: 'Eradikasi malai tercekik busuk.',
    biologicalControl: 'Bakteri antagonis Pseudomonas fluorescens.',
    chemicalControl: 'Fungisida protektif dan kuratif saat fase bunting menjelang keluar malai.',
    activeIngredients: ['Trisiklazol', 'Karbendazim', 'Difenokonazol'],
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-gulma-eceng-padi',
    commonName: 'Gulma Eceng Padi / Wewehan',
    scientificName: 'Monochoria vaginalis',
    category: 'WEED',
    aliases: ['Eceng Padi', 'Wewehan', 'Eceng Lembut', 'Broadleaf Weed'],
    symptoms: 'Tumbuh lebat di sela rumpun padi; bersaing ketat memperebutkan unsur hara Nitrogen, air, dan cahaya matahari pada awal musim tanam.',
    lifeCycle: 'Biji berkecambah cepat di tanah tergenang dangkal; berbunga ungu kebiruan menghasilkan ribuan biji tahan dormansi.',
    hostPlants: ['Sawah irigasi tergenang'],
    vulnerableStage: '0-30 HST (Fase Kritis Kompetisi Gulma)',
    triggerFactors: ['Genangan air dangkal berlumpur dengan pencahayaan tinggi pada 2 minggu awal tanam'],
    monitoringMethod: 'Amati kerapatan populasi gulma berdaun lebar di antara lorong tanam.',
    economicThreshold: 'Penutupan gulma > 15% dari luas petakan.',
    culturalControl: 'Pengolahan tanah sempurna (singkal, rotari, garu rata), sistem tanam Jajar Legowo memudahkan penyiangan.',
    mechanicalControl: 'Penyiangan mekanis dengan gasrok/landak pada umur 15 dan 35 HST.',
    biologicalControl: 'Pemanfaatan bebek untuk memakan kecambah gulma.',
    chemicalControl: 'Herbisida pra-tumbuh atau purna-tumbuh selektif berdaun lebar bila tenaga kerja penyiangan terbatas.',
    activeIngredients: ['2,4-D Dimetil Amina', 'Bispiribak-sodium', 'Metil Metsulfuron'],
    referenceId: 'ref-gulma-padi-2022',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-gulma-jajagoan',
    commonName: 'Gulma Jajagoan / Rumput Bebek',
    scientificName: 'Echinochloa crus-galli / Echinochloa colona',
    category: 'WEED',
    aliases: ['Jajagoan', 'Rumput Bebek', 'Rumput Tekian Rumput', 'Barnyard Grass'],
    symptoms: 'Bentuk morfologi anakan sangat menyerupai tanaman padi muda; menyerap N sangat rakus dan menjadi inang penggerek dan wereng.',
    lifeCycle: 'Biji berkecambah serempak dengan benih padi; tumbuh lebih tinggi dan menaungi rumpun padi.',
    hostPlants: ['Sawah irigasi & sawah tadah hujan'],
    vulnerableStage: '0-35 HST',
    triggerFactors: ['Pengeringan petak sawah terlalu dini pada minggu ke-1 setelah tanam'],
    monitoringMethod: 'Periksa sela barisan rumpun terhadap rumput tegak berdaun pita tanpa lidah daun (ligula).',
    economicThreshold: 'Populasi > 5 tanaman jajagoan per m².',
    culturalControl: 'Genangi air sawah 2-3 cm pada 1-7 HST untuk menekan perkecambahan biji gulma rumput.',
    mechanicalControl: 'Cabut manual saat penyiangan ke-1 (sebelum berbunga).',
    biologicalControl: 'Pengolahan tanah basah matang.',
    chemicalControl: 'Herbisida selektif purna-tumbuh khusus padi sawah.',
    activeIngredients: ['Butaklor', 'Pretilaklor', 'Fenoksaprop-p-etil', 'Bispiribak-sodium'],
    referenceId: 'ref-gulma-padi-2022',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'opt-gulma-teki-sawah',
    commonName: 'Gulma Teki Sawah / Teki Pendul',
    scientificName: 'Cyperus difformis / Fimbristylis miliacea',
    category: 'WEED',
    aliases: ['Teki Sawah', 'Teki Pendul', 'Sunduk Welut', 'Sedge Weed'],
    symptoms: 'Batang berbentuk segitiga berongga dengan bunga payung bertumpuk; menyerap hara fosfat dan kalium tanah secara agresif.',
    lifeCycle: 'Berkembang biak lewat umbi dan biji melimpah yang tahan berada di dalam lumpur.',
    hostPlants: ['Sawah irigasi'],
    vulnerableStage: '0-30 HST',
    triggerFactors: ['Tanah sawah lembap tidak tergenang sempurna pada awal tanam'],
    monitoringMethod: 'Amati rumpun teki berbatang segitiga di petakan.',
    economicThreshold: 'Kepadatan > 10 rumpun teki per m².',
    culturalControl: 'Genangan air teratur 3 cm pada fase awal tanam.',
    mechanicalControl: 'Penyiangan dengan landak/gasrok memotong umbi teki.',
    biologicalControl: 'Dekomposisi jerami saat olah tanah.',
    chemicalControl: 'Herbisida purna-tumbuh selektif berbahan aktif etoksisulfuron.',
    activeIngredients: ['Etoksisulfuron', 'Metil Metsulfuron', 'Bispiribak-sodium'],
    referenceId: 'ref-gulma-padi-2022',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

export const SEED_NATURAL_ENEMIES: NaturalEnemy[] = [
  {
    id: 'enemy-laba-serigala',
    name: 'Laba-laba Serigala Pemburu',
    scientificName: 'Pardosa pseudoannulata',
    type: 'PREDATOR',
    targetOptIds: ['opt-wereng-coklat', 'opt-penggerek-kuning'],
    attackedStages: ['Nimfa', 'Imago/Dewasa'],
    habitat: 'Pangkal batang padi dan permukaan air sawah.',
    conservationNotes: 'Pertahankan petak sawah dari aplikasi insektisida semprotan langsung ke pangkal batang jika populasi laba-laba tinggi (1 ekor/rumpun).',
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'enemy-kumbang-kubah',
    name: 'Kumbang Kubah Bergaris',
    scientificName: 'Micraspis crocea',
    type: 'PREDATOR',
    targetOptIds: ['opt-wereng-coklat', 'opt-walang-sangit'],
    attackedStages: ['Telur', 'Nimfa muda'],
    habitat: 'Kanopi daun bagian atas dan malai.',
    conservationNotes: 'Tanam tanaman refugia berbunga kuning (kenikir, bunga tahi ayam) di pematang sawah sebagai sumber nektar alternatif.',
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'enemy-trichogramma',
    name: 'Tawon Parasitoid Telur',
    scientificName: 'Trichogramma japonicum',
    type: 'PARASITOID',
    targetOptIds: ['opt-penggerek-kuning'],
    attackedStages: ['Telur'],
    habitat: 'Bebas terbang di kanopi persawahan.',
    conservationNotes: 'Sangat rentan terhadap kabut insektisida kimia; hindari penyemprotan rutin terjadwal.',
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'enemy-kepik-mirid',
    name: 'Kepik Mirid Pemangsa Telur',
    scientificName: 'Cyrtorhinus lividipennis',
    type: 'PREDATOR',
    targetOptIds: ['opt-wereng-coklat'],
    attackedStages: ['Telur', 'Nimfa muda'],
    habitat: 'Pangkal batang dan pelepah daun padi.',
    conservationNotes: 'Kepik ini sangat efektif memangsa telur wereng di dalam jaringan pelepah.',
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'enemy-burung-hantu',
    name: 'Burung Hantu Tyto alba',
    scientificName: 'Tyto alba javanica',
    type: 'PREDATOR',
    targetOptIds: ['opt-tikus-sawah'],
    attackedStages: ['Dewasa', 'Anak Tikus'],
    habitat: 'Kandang / Rumah Burung Hantu (Rubuha) di tengah hamparan sawah.',
    conservationNotes: 'Satu pasang Tyto alba mampu memangsa 2-5 ekor tikus per malam; lindungi sarang dari perburuan liar.',
    referenceId: 'ref-bbpopt-tikus-2021',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'enemy-kumbang-tomcat',
    name: 'Kumbang Jelajah / Tomcat',
    scientificName: 'Paederus fuscipes',
    type: 'PREDATOR',
    targetOptIds: ['opt-wereng-coklat', 'opt-penggerek-kuning', 'opt-wereng-daun-hijau'],
    attackedStages: ['Nimfa', 'Larva kecil'],
    habitat: 'Permukaan tanah dan tajuk tanaman padi.',
    conservationNotes: 'Predator generalis yang sangat rakus memangsa wereng muda.',
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'enemy-capung-jarum',
    name: 'Capung Jarum Sawah',
    scientificName: 'Agriocnemis femina',
    type: 'PREDATOR',
    targetOptIds: ['opt-wereng-coklat', 'opt-wereng-daun-hijau', 'opt-penggerek-kuning'],
    attackedStages: ['Imago/Dewasa terbang', 'Nimfa'],
    habitat: 'Terbang rendah di kanopi dan sela-sela rumpun padi.',
    conservationNotes: 'Pertahankan kualitas air sawah bebas dari residu insektisida beracun agar nimfa capung air dapat berkembang biak.',
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'enemy-katak-sawah',
    name: 'Katak Sawah / Fejervarya',
    scientificName: 'Fejervarya cancrivora',
    type: 'PREDATOR',
    targetOptIds: ['opt-orong-orong', 'opt-ulat-grayak', 'opt-walang-sangit'],
    attackedStages: ['Larva', 'Nimfa', 'Imago/Dewasa'],
    habitat: 'Lumpur sawah, pematang basah, dan saluran cacing.',
    conservationNotes: 'Predator malam hari yang rakus; kurangi penggunaan pestisida kimia spektrum luas yang meracuni amfibi.',
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'enemy-jamur-beauveria',
    name: 'Jamur Entomopatogen Beauveria bassiana',
    scientificName: 'Beauveria bassiana',
    type: 'ENTOMOPATHOGEN',
    targetOptIds: ['opt-wereng-coklat', 'opt-walang-sangit', 'opt-kepinding-tanah'],
    attackedStages: ['Nimfa', 'Imago/Dewasa'],
    habitat: 'Disemprotkan ke kanopi dan pangkal rumpun padi saat sore hari.',
    conservationNotes: 'Efektif menginfeksi serangga hama hingga tubuhnya tertutup miselium putih kapur (white muscardine).',
    referenceId: 'ref-pht-padi-2019',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'enemy-bakteri-paenibacillus',
    name: 'Bakteri Antagonis Paenibacillus polymyxa',
    scientificName: 'Paenibacillus polymyxa',
    type: 'OTHER',
    targetOptIds: ['opt-hawar-daun-bakteri', 'opt-blas-padi'],
    attackedStages: ['Spora Patogen', 'Koloni Bakteri'],
    habitat: 'Perakaran, benih perendaman, dan permukaan daun.',
    conservationNotes: 'Menghasilkan metabolit antibakteri dan antifungi serta memicu induksi ketahanan sistemik tanaman.',
    referenceId: 'ref-litbang-padi-2020',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

export const SEED_KNOWLEDGE_ARTICLES: KnowledgeArticle[] = [
  {
    id: 'art-pupuk-berimbang',
    category: 'FERTILIZATION',
    title: 'Prinsip Dasar Pemupukan Padi Berimbang (5T)',
    summary: 'Panduan pemupukan padi yang tepat jenis, tepat dosis, tepat waktu, tepat cara, dan tepat mutu berdasarkan kaidah Balittanah Kementan RI.',
    content: `Pemupukan berimbang adalah pemberian pupuk ke dalam tanah dengan jumlah dan jenis hara yang sesuai dengan tingkat kesuburan tanah dan kebutuhan fisiologis tanaman.

Prinsip 5 Tepat:
1. **Tepat Jenis**: Memberikan pupuk sesuai kekurangan unsur hara tanah (N, P, K, S, dll).
2. **Tepat Dosis**: Menyesuaikan target hasil dan kelas kesuburan tanah, menghindari kelebihan Urea yang memicu tanaman sukulen, mudah rebah, dan rentan serangan hama.
3. **Tepat Waktu**: Diberikan pada fase serapan aktif tanaman (Pupuk Dasar 0-7 HST, Anakan Aktif 21-25 HST, dan Primordia/Bunting 40-45 HST).
4. **Tepat Cara**: Ditabur merata saat kondisi air macak-macak (tidak tergenang dalam agar pupuk tidak larut terbuang ke saluran pembuangan).
5. **Tepat Mutu**: Menggunakan pupuk resmi berlabel SNI dan nomor pendaftaran Kementan yang sah.`,
    tags: ['Pemupukan', 'Hara', 'Urea', 'NPK', 'Dasar', 'Balittanah'],
    referenceId: 'ref-pupuk-kementan-2021',
    verifiedDate: '2026-01-15T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'art-pht-dasar',
    category: 'PEST_DISEASE',
    title: 'Prinsip Pengendalian Hama Terpadu (PHT) pada Padi Sawah',
    summary: 'Mengenal konsep 4 pilar PHT: budidaya tanaman sehat, pelestarian musuh alami, pengamatan mingguan rutin, dan petani sebagai ahli PHT di lahannya.',
    content: `Pengendalian Hama Terpadu (PHT) bukan berarti tidak boleh menyemprot pestisida kimia, melainkan menempatkan pestisida kimia sebagai jalan terakhir bila populasi hama melampaui ambang kendali ekonomi.

4 Pilar Utama PHT Padi:
1. **Budidaya Tanaman Sehat**: Benih unggul bersertifikat, jarak tanam teratur (Jajar Legowo), pemupukan berimbang spesifik lokasi, dan pengairan berselang.
2. **Pelestarian & Pemanfaatan Musuh Alami**: Menjaga predator alami (laba-laba, kumbang kubah, kepik mirid, parasitoid telur) dengan menanam tanaman berbunga (refugia) di pematang.
3. **Pengamatan Mingguan Teratur**: Petani memantau petak sawahnya minimal seminggu sekali untuk mengetahui rasio hama dan musuh alami secara dini.
4. **Petani Sebagai Ahli PHT**: Petani mengambil keputusan pengendalian secara mandiri berdasarkan fakta lapang nyata.`,
    tags: ['PHT', 'OPT', 'Musuh Alami', 'Pengamatan', 'Ditlin'],
    referenceId: 'ref-pht-padi-2019',
    verifiedDate: '2026-01-15T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'art-jajar-legowo',
    category: 'CULTIVATION',
    title: 'Sistem Tanam Jajar Legowo 2:1 untuk Padi Sawah',
    summary: 'Meningkatkan populasi rumpun hingga 33% per hektar dan memaksimalkan efek tanaman pinggir yang lebih produktif.',
    content: `Sistem tanam Jajar Legowo 2:1 adalah cara tanam berselang antara dua baris tanaman dan satu baris kosong dengan jarak antar baris 20-25 cm dan jarak dalam baris 10-12.5 cm.

Keunggulan Jajar Legowo 2:1:
1. **Peningkatan Populasi**: Menambah populasi rumpun tanaman hingga 213.300 rumpun/ha dibandingkan tegel 25x25 cm (160.000 rumpun/ha).
2. **Efek Tanaman Pinggir (Border Effect)**: Seluruh barisan tanaman mendapat sirkulasi udara dan radiasi sinar matahari optimal sehingga fotosintesis lebih tinggi.
3. **Kemudahan Pemeliharaan**: Lorong kosong memudahkan pemupukan susulan, penyiangan gulma, dan penyemprotan OPT.
4. **Menekan Kelembapan Mikro**: Mengurangi risiko perkembangan penyakit jamur Blas dan Hawar Daun Bakteri.`,
    tags: ['Budidaya', 'Jajar Legowo', 'Tanam', 'Populasi', 'BBPadi'],
    referenceId: 'ref-litbang-padi-2020',
    verifiedDate: '2026-01-20T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'art-pengairan-berselang',
    category: 'IRRIGATION',
    title: 'Teknik Pengairan Berselang (Intermittent / AWD) pada Sawah',
    summary: 'Pengaturan air sawah tergenang dan kering secara bergantian untuk menghemat air 20-30%, mencegah rebah, dan merangsang perakaran dalam.',
    content: `Pengairan berselang (Alternate Wetting and Drying / AWD) adalah teknik pengaturan air kondisi tergenang dan kering secara berkala sesuai kebutuhan fase pertumbuhan padi.

Jadwal Pelaksanaan Pengairan:
- **0-7 HST (Adaptasi)**: Tergenang dangkal (1-2 cm) untuk mencegah bibit hanyut dan menekan gulma awal.
- **8-35 HST (Anakan Aktif)**: Terapkan pengairan berselang; biarkan petak sawah surut hingga tanah sedikit retak rambut (retak halus), lalu airi kembali setinggi 3 cm.
- **40-65 HST (Bunting - Berbunga Penuh)**: Wajib tergenang dangkal (3-5 cm) karena tanaman sangat sensitif terhadap kekurangan air saat pembentukan malai dan sari.
- **70-85 HST (Pengisian Bulir)**: Pengairan berselang kembali (kondisi macak-macak).
- **10-14 Hari Sebelum Panen**: Keringkan petak sawah secara total untuk mematangkan gabah serempak dan mempermudah panen.`,
    tags: ['Irigasi', 'Air Berselang', 'AWD', 'Macak-Macak', 'IRRI'],
    referenceId: 'ref-irri-rice-knowledge',
    verifiedDate: '2026-01-20T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'art-manajemen-persemaian',
    category: 'CULTIVATION',
    title: 'Panduan Persemaian Padi Sehat & Pencegahan Dini OPT',
    summary: 'Langkah kunci seleksi benih bernas dengan larutan garam, perlakuan benih (seed treatment), dan pemeliharaan bibit prima.',
    content: `Persemaian adalah fondasi utama keberhasilan budidaya padi. Bibit yang sehat, kokoh, dan bebas patogen akan tumbuh cepat setelah pindah tanam.

Tahapan Persemaian Prima:
1. **Uji Benih Bernas (Larutan Garam)**: Masukkan telur ayam mentah ke dalam air, tambahkan garam dapur sampai telur terapung di permukaan. Masukkan benih padi; gunakan hanya benih yang tenggelam di dasar wadah, lalu bilas air bersih.
2. **Perlakuan Benih (Seed Treatment)**: Rendam benih bernas selama 24 jam dengan agens hayati Paenibacillus polymyxa atau fungisida perlakuan benih untuk membunuh spora jamur bawaan.
3. **Pemeraman**: Peram benih di karung goni basah selama 24-48 jam sampai titik tumbuh akar (radikula) muncul 1-2 mm.
4. **Bedengan Persemaian**: Buat bedengan lebar 1-1.2 m, tabur pupuk organik matang merata. Tabur benih dengan kerapatan tidak terlalu padat (25-30 gram benih/m²).
5. **Umur Pindah Tanam**: Bibit dipindahtanamkan pada umur 15-21 hari setelah sebar (HSS) dengan daun 3-4 helai.`,
    tags: ['Persemaian', 'Bibit', 'Benih Bernas', 'Seedbed', 'BBPadi'],
    referenceId: 'ref-litbang-padi-2020',
    verifiedDate: '2026-01-22T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'art-tikus-tbs-manajemen',
    category: 'PEST_DISEASE',
    title: 'Teknologi Pengendalian Hama Tikus Berbasis LTBS & TBS',
    summary: 'Metode pengendalian tikus sawah ramah lingkungan dengan sistem bubu perangkap tanpa racun berbahaya.',
    content: `Tikus sawah (Rattus argentiventer) merupakan salah satu hama utama yang menyerang sejak awal musim tanam hingga panen.

Metode Pengendalian Terpadu:
1. **Gropyokan Massal Pratanam**: Dilakukan bersama seluruh kelompok tani saat pengolahan tanah awal sebelum tikus memasuki masa kawin.
2. **Linear Trap Barrier System (LTBS)**: Bentangan pagar plastik setinggi 50-60 cm sepanjang 100-200 meter di batas habitat tikus dengan bubu perangkap setiap 20 meter.
3. **Trap Barrier System (TBS)**: Petak tanaman perangkap berukuran 20x20 m yang ditanam 2-3 minggu lebih awal dari hamparan sekitarnya, dipagar plastik dengan bubu penangkap.
4. **Konservasi Burung Hantu Tyto alba**: Pemasangan Rumah Burung Hantu (Rubuha) untuk perkembangbiakan predator alami.
5. **Sanitasi Pematang**: Perkecil pematang sawah (< 30 cm) agar tikus tidak nyaman bersarang.`,
    tags: ['Tikus', 'TBS', 'LTBS', 'Tyto alba', 'BBPOPT'],
    referenceId: 'ref-bbpopt-tikus-2021',
    verifiedDate: '2026-01-22T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'art-panen-pasca-panen',
    category: 'HARVEST',
    title: 'Tanda Kematangan Optimal & Penanganan Panen Padi',
    summary: 'Mencegah kehilangan hasil saat panen dengan menentukan umur panen dan kadar air gabah yang tepat.',
    content: `Waktu panen yang tepat sangat menentukan mutu beras (rendemen beras kepala tinggi dan menekan beras patah).

Tanda Padi Siap Panen:
1. **Kuning Malai**: 90-95% bulir gabah pada malai telah menguning sempurna.
2. **Daun Bendera**: Daun bendera telah menguning atau mengering secara alami.
3. **Kadar Air**: Kadar air gabah ideal saat panen berada pada kisaran 21-24%.
4. **Pencegahan Kehilangan Hasil**: Gunakan alas terpal bersih saat perontokan manual atau gunakan Combine Harvester dengan setelan blower optimal.`,
    tags: ['Panen', 'Kadar Air', 'GKP', 'Rendemen', 'BBPadi'],
    referenceId: 'ref-litbang-padi-2020',
    verifiedDate: '2026-01-20T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'art-pengendalian-gulma-sawah',
    category: 'WEED_MANAGEMENT',
    title: 'Strategi Pengendalian Gulma Terpadu pada Ekosistem Padi Sawah',
    summary: 'Mencegah kehilangan hasil hingga 30% akibat persaingan gulma pada periode kritis 0-35 HST.',
    content: `Periode kritis persaingan gulma dengan tanaman padi terjadi pada sepertiga awal siklus hidupnya (0-35 HST).

Langkah Pengelolaan Gulma Terpadu:
1. **Pengolahan Tanah Sempurna**: Pembajakan dan penggaruan dua kali yang diselingi perataan lumpur menenggelamkan biji gulma ke lapisan anaerobik.
2. **Manajemen Air Awal**: Menggenangi petak sawah setinggi 2-3 cm pada 1-7 HST efektif menekan perkecambahan biji gulma rumput dan teki.
3. **Sistem Jajar Legowo**: Memberikan ruang lorong teratur untuk penyiangan menggunakan alat mekanis (landak/gasrok) pada umur 15 dan 30 HST.
4. **Sanitasi Pematang**: Memotong rumput pematang sebelum berbunga agar biji gulma tidak terbawa angin atau air ke dalam petakan sawah.`,
    tags: ['Gulma', 'Penyiangan', 'Gasrok', 'Periode Kritis', 'BBPadi'],
    referenceId: 'ref-gulma-padi-2022',
    verifiedDate: '2026-01-25T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'art-busuk-pelepah-manajemen',
    category: 'PEST_DISEASE',
    title: 'Diagnosis & Manajemen Penyakit Busuk Pelepah (Rhizoctonia solani)',
    summary: 'Mencegah infeksi sklerosia jamur tanah yang menyerang pelepah pada kondisi pertanaman rapat dan lembap.',
    content: `Busuk pelepah (Sheath Blight) disebabkan oleh jamur tular-tanah Rhizoctonia solani yang membentuk struktur dorman sklerosia tahan bertahun-tahun di tanah sawah.

Strategi Pengendalian:
1. **Atur Jarak Tanam**: Hindari jarak tanam terlalu rapat (< 20x20 cm) dan terapkan Jajar Legowo 2:1 untuk memperlancar sirkulasi udara di kanopi bawah.
2. **Keseimbangan Hara N dan K**: Hindari dosis pupuk Urea berlebih dan tingkatkan pupuk KCl/Kalium untuk mempertebal dinding sel pelepah.
3. **Pengairan Berselang (AWD)**: Pengeringan berkala menurunkan kelembapan mikro tanah.
4. **Agens Hayati**: Aplikasi jamur antagonis Trichoderma harzianum saat olah tanah dan pupuk kandang.`,
    tags: ['Busuk Pelepah', 'Rhizoctonia', 'Penyakit Jamur', 'Sheath Blight', 'BBPadi'],
    referenceId: 'ref-litbang-padi-2020',
    verifiedDate: '2026-01-25T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'art-refugia-konservasi',
    category: 'PEST_DISEASE',
    title: 'Pemanfaatan Tanaman Refugia di Pematang untuk Konservasi Musuh Alami',
    summary: 'Menanam bunga kenikir, zinnia, dan tahi ayam untuk menyediakan nektar dan mikroklimat bagi predator hama.',
    content: `Tanaman refugia adalah tumbuhan berbunga yang ditanam di sekitar lahan pertanian sebagai tempat berlindung, sumber pakan nektar/polen, dan tempat bertelur musuh alami.

Jenis Tanaman Refugia Rekomendasi:
1. **Kenikir (Cosmos caudatus)**: Bunga mekar terus menerus, sangat disukai lebah dan tawon parasitoid Trichogramma.
2. **Bunga Tahi Ayam (Tagetes erecta)**: Mengandung senyawa alami yang mengusir serangga hama pengganggu dan menarik kumbang kubah.
3. **Bunga Kertas / Zinnia**: Menarik laba-laba dan serangga predator terbang.
4. **Kacang Panjang / Buncis di Pematang**: Selain sumber refugia, memberikan nilai ekonomi tambahan bagi keluarga petani.`,
    tags: ['Refugia', 'Musuh Alami', 'Kenikir', 'PHT', 'Ditlin'],
    referenceId: 'ref-pht-padi-2019',
    verifiedDate: '2026-01-25T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'art-silika-padi',
    category: 'FERTILIZATION',
    title: 'Peran Unsur Silika (Si) dalam Meningkatkan Ketahanan Fisik Daun Padi',
    summary: 'Mencegah serangan penggerek batang dan jamur blas dengan mempertebal lapisan silikasi kutikula daun.',
    content: `Padi adalah tanaman akumulator silika (Si). Kadar silika dalam jerami padi normal berkisar antara 10-15%.

Manfaat Silika bagi Padi:
1. **Ketahanan Mekanis Hama**: Silika terakumulasi di lapisan sel epidermis membentuk fitolit ganda yang keras, membuat mandibel larva penggerek batang dan stilet wereng aus/patah.
2. **Ketahanan Penyakit**: Membentuk perisai fisik yang menghambat penetrasi hifa jamur Blas (Pyricularia oryzae).
3. **Daun Lebih Tegak**: Memperbaiki arsitektur tajuk daun sehingga fotosintesis maksimal dan menekan kelembapan mikro.
4. **Sumber Silika Alami**: Pengembalian abu sekam bakar (rich silica) dan jerami yang dikomposkan ke petak sawah.`,
    tags: ['Silika', 'Pupuk Si', 'Ketahanan Fisik', 'Blas', 'Balittanah'],
    referenceId: 'ref-pupuk-kementan-2021',
    verifiedDate: '2026-01-25T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'art-pupuk-kandang-matang',
    category: 'FERTILIZATION',
    title: 'Restorasi Bahan Organik Sawah dengan Kompos / Pupuk Kandang Matang',
    summary: 'Memperbaiki struktur tanah sawah, menaikkan pH tanah masam, dan meningkatkan kapasitas tukar kation (KTK).',
    content: `Kandungan C-organik tanah sawah intensif di Indonesia banyak yang berada di bawah level kritis (< 1.5%). Penggunaan pupuk anorganik terus-menerus tanpa bahan organik menyebabkan tanah mengeras (bantat) dan boros pupuk.

Pedoman Penggunaan Pupuk Kandang:
1. **Wajib Matang Sempurna**: Gunakan pupuk kandang yang sudah difermentasi dingin (suhu ruang, tidak berbau busuk amonia menyengat, warna coklat kehitaman remah).
2. **Dosis Rekomendasi**: 1.000 - 2.000 kg/ha diaplikasikan saat olah tanah pertama (pembajakan).
3. **Efek Jangka Panjang**: Meningkatkan populasi mikroba tanah yang bermanfaat, melarutkan fosfat terikat, dan mengurangi kebutuhan pupuk kimia 15-20%.`,
    tags: ['Pupuk Organik', 'Bahan Organik', 'C-Organik', 'Kesuburan Tanah', 'Balittanah'],
    referenceId: 'ref-pupuk-kementan-2021',
    verifiedDate: '2026-01-25T00:00:00.000Z',
    status: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];
